const $=id=>document.getElementById(id),fmt=(x,d=4)=>Number.isFinite(x)?(Math.abs(x)<.5*10**(-d)?0:+x.toFixed(d)).toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
let active=1,last=null;const modeSnapshots={};
function clampBudgetInput(input,commit=false){const raw=String(input.value);if(raw.trim()===''){if(commit)input.value=String(input.defaultValue||0);return}const v=Number(raw);if(!Number.isFinite(v)){if(commit)input.value=String(input.defaultValue||0);return}const low=Number(input.min)||0,high=Number(input.max);input.value=String(Math.max(low,Math.min(high,Math.floor(v))))}
function cfg(){for(const k of Object.keys(MIX_LIMITS))clampBudgetInput($('budget_'+k),true);const free=active===2;return {region:$('region').value,crystal:+$('crystal').value,calcGoal:free?2:1,unifiedFree:free,unifiedPhase:typeof unifiedPhase==='undefined'?1:unifiedPhase,fixedTargets:free?readPlanRows('fixed'):[],nextTargets:free&&typeof unifiedPhase!=='undefined'&&unifiedPhase===2?readPlanRows('next'):[],expectTargets:[],expectCatalog:typeof RECIPE_PACKAGE!=='undefined'?RECIPE_PACKAGE.recipes:[],budgets:Object.fromEntries(Object.keys(MIX_LIMITS).map(k=>[k,+$('budget_'+k).value])),free,freeTargets:[],ore:+$('ore').value,blue:+$('blue').value,copper:+$('copper').value,solid:+$('solid').value,gas:+$('gas').value,powder:$('transport').value==='powder'?+$('transportAmount').value:0,blueTransport:$('transport').value==='blue'?+$('transportAmount').value:0,power:$('useMidPower').checked?+$('power').value:0,lowPower:$('useLowPower').checked?+$('lowPower').value:0,threshold:+$('threshold').value,node:$('node').checked,waste:+$('waste').value,acidCost:+$('acidCost').value,activity:$('activity').checked,conversion:$('conversion').value,liquid:$('liquid').value==='yes',mode:$('mode').value,products:[...document.querySelectorAll('.goods:checked')].map(x=>x.value)}}
const names=['低电','蓝药','紫药','中电','赫铜','重息壤','灼铜'];$('goods').innerHTML=names.map(x=>`<label class="chip"><input class="goods" type="checkbox" value="${x}" checked>${x}</label>`).join('');
function state(){$('waste').disabled=!$('node').checked;$('power').disabled=!$('useMidPower').checked;$('lowPower').disabled=!$('useLowPower').checked;const base=$('current').checked;for(const[k,v]of Object.entries($('region').value==='valley'?{ore:560,blue:1080,crystal:240,copper:0,solid:0,gas:0}:{ore:540,blue:120,crystal:0,copper:510,solid:360,gas:150})){if(base)$(k).value=v;$(k).disabled=base}const preset=$('engineerPreset').checked?'engineering':$('extremePreset').checked?'continuous':null;if(preset){$('conversion').value=preset==='engineering'?'S':'L';$('liquid').value=preset==='engineering'?'no':'yes';$('mode').value='continuous'}for(const k of ['conversion','liquid','mode'])$(k).disabled=!!preset;const v=$('transport').value,a=+$('transportAmount').value;$('transportNote').textContent=v==='powder'?`${fmt(a/60)}粉末/min；等价${fmt(a/30)}原矿/min，仍按粉末记账`:v==='blue'?`${fmt(a/60)}蓝铁/min`:'不计外运';$('continuousBudgets').hidden=$('mode').value!=='continuous';$('versionState').textContent=base?'当前版本基础资源已锁定':'自定义资源';}
$('engineerPreset').onchange=()=>{if($('engineerPreset').checked)$('extremePreset').checked=false;state()};$('extremePreset').onchange=()=>{if($('extremePreset').checked)$('engineerPreset').checked=false;state()};$('current').onchange=state;$('node').onchange=state;$('useMidPower').onchange=state;$('useLowPower').onchange=state;$('transport').onchange=state;$('transportAmount').oninput=state;
function take(v){return engineeringText(v,false)}
function occupiedCost(p,r,c,result){if(p.furnace)return 30*Math.ceil(r-1e-7);if(!p.environment)return 0;if(!result)return c.acidCost*Math.ceil(r/p.occupancyCapacity-1e-7);const first=result.recipes.findIndex((t,i)=>t.environment===p.environment&&result.r[i]>1e-6);return result.recipes[first]?.id===p.id?c.acidCost*(result.count[p.environment]||0):0}
function productRaw(p,r,ns,result){let raw=p.raw.map(x=>x*r);raw[3]-=9.6*ns;return raw}
function control(p,r,ns,result){if(p.withdraw)return '自用留存，不是额外生产设备';if(p.network){const input=p.sourceRecipe.inputs.find(x=>x.amount>0);const v=input?input.amount*60/p.sourceRecipe.seconds*r:0;return input?input.item+' '+fmt(v,6)+'/min：'+(result.mode==='continuous'?mixedText(v,/气|液|水|酸/.test(input.item),result.budgets):engineeringText(v,/气|液|水|酸/.test(input.item)))+'；其余投入按配方配平':'查看配方资源包';}let raw=productRaw(p,r,ns,result);const options=raw.map((v,i)=>({v,i})).filter(x=>x.v>1e-7&&standard(x.v)&&!(p.up==='L'&&x.i===3));if(p.reaction*r>0&&standard(p.reaction*r))options.push({v:p.reaction*r,i:4});if(result.mode==='continuous')return freeControl(p,r,ns,result);if(!options.length)return '共享中间设备直连；需核对分流接法';options.sort((a,b)=>engineeringTake(a.v,a.i===4).cost-engineeringTake(b.v,b.i===4).cost);const x=options[0];return ['原矿','蓝铁','赤铜','普通息壤','普通反应气'][x.i]+'：'+engineeringText(x.v,x.i===4)+'。其他普通料足量供给、回堵控速。'}
function rowsTable(head,rows){return `<div class="table-scroll"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function render(){if($('region').value==='valley'){$('results').innerHTML='<div class="empty">四号谷地计算暂未开放；当前仅提供资源与选项框架。谷地不支持清水、污水等各类水相关配方。</div>';return;}if(last?.cfg.free){renderFree();return}if(active===3){$('results').innerHTML='<div class="empty">填写自由产率后点击计算。</div>';return}const c=last?.cfg,res=last?.result?.[active===1?'first':'second'];if(!c){$('results').innerHTML='<div class="empty">该模式尚未计算，请填写输入后点击当前模式的计算按钮。</div>';return;}if(!res){$('results').innerHTML=`<div class="empty"><h3>没有找到满足条件的方案</h3><p>${active===2?'所选自用最低产率与期望兑换额度可能无法同时满足；请减少调整产率或降低额度。未找到候选也可能是搜索达到限制，可用连续解复核。':'检查中电是否允许、供电需求及原料容量。'}</p></div>`;return}res.budgets=c.budgets;const hourly=res.rev*60,difference=Math.abs(hourly-c.threshold)<1e-4?0:hourly-c.threshold;let upper=res.upper;if(active===1&&res.mode==='engineering')upper-=powerCost(c);const headline=active===1?'最大调度券产值':'期望兑换';$('results').innerHTML=`<div class="result-head"><div><span class="eyebrow">${headline}</span><h2>${active===1?fmt(hourly,2)+' <small>价值/h</small>':'期望兑换 <small>优先级规划</small>'}</h2></div><span class="badge">${{integer:'整数解',engineering:'工程候选解',continuous:'连续流量＋固定占用'}[res.mode]}</span></div><div class="stats"><div><label>扣供电售卖价值/min</label><strong>${fmt(res.rev)}</strong></div><div><label>相对期望额度/h</label><strong class="${difference>=-1e-3?'positive':'negative'}">${difference>=0?'+':''}${fmt(difference,2)}</strong></div><div><label>普通转气息壤主输入/min</label><strong>${fmt(res.B)}</strong></div><div><label>转气等价满速 / 启用机台</label><strong>${fmt(res.B/30)} / ${fmt(res.nc)}</strong></div></div><p class="result-note">${res.certificate}${res.mode==='engineering'?`；${active===1?'售卖价值':'首项产率'}上界 ${fmt(upper)}${active===1?'/min':'/min'}。`:''} 赫铜瓶售价未给出，不计调度券价值。</p>`;
 if(active===2&&res.priority){$('results').innerHTML+=rowsTable(['优先级','自用产物','实际产率/min','调整最低量/min'],res.priority.map((t,i)=>[i+1,t.name,fmt(t.rate<1e-6?0:t.rate,6),fmt(t.min)]));if(!res.priority.length)$('results').innerHTML+='<p>五个目标均为空：仅规划达到期望额度的售卖组合。填写目标后重新计算。</p>';expectApplyResult(res);} const rr=[];res.recipes.forEach((p,i)=>{let r=res.r[i];if(r<1e-6)return;let qty=p.out*r,sale=p.expect?0:qty-powerFor(c,p.id);rr.push([p.name,p.route,fmt(qty),fmt(r),fmt(sale),p.expect?'自用／中间加工，不售卖':p.bottle?'未计价':fmt(sale*p.price)])});$('results').innerHTML+=rowsTable(['产物','工艺','产量/min','等价满速','售卖量/min','价值/min'],rr);
 const rawRows=res.raw.map((v,i)=>{let cap=[c.ore+2*c.powder/60,c.blue+c.blueTransport/60,c.copper,c.solid][i];return [['原矿等价量','蓝铁等价量','赤铜','息壤'][i],fmt(v),fmt(cap-v)]});rawRows.push(['天然息壤气',fmt(res.externalGas),fmt(c.gas-res.externalGas)]);if((res.gasSurplus||0)>1e-7)rawRows.push(['自产息壤气富余',fmt(res.gasSurplus),'单独列示，不计入天然气剩余']);$('results').innerHTML+=`<h3>资源账</h3>`+rowsTable(['基础资源/min','实际使用','剩余'],rawRows)+`<p class="hint">原矿等价量仅用于容量核算；外运粉末为${fmt(c.powder/60)}个/min。中电需要${fmt(res.recipes.reduce((s,p,i)=>s+(p.id==='mid'?120*res.r[i]:0),0))}致密原石粉末/min，不能把外运粉末当成实际原矿取货。</p>`;
 if(res.mode!=='integer'){const tr=[];res.recipes.forEach((p,i)=>{let r=res.r[i];if(r<1e-6)return;let raw=productRaw(p,r,res.ns?.[i]||0,res);tr.push([p.name+' · '+p.route,raw.map((v,j)=>v>1e-6?['原矿等价','蓝铁','赤铜','息壤'][j]+' '+fmt(v):'').filter(Boolean).join('；'),control(p,r,res.ns?.[i]||0,res),fmt(occupiedCost(p,r,c,res)),fmt(p.reaction*r)])});$('results').innerHTML+=`<h3>基础原料取货与反应气</h3>`+rowsTable(['产线','普通原料消耗/min','全部普通原料接法','固定占用息壤/min','反应气/min'],tr)+`<p class="hint">灼铜三种工艺共用的环境占用只列在首条启用灼铜线上。部分工艺共享上游激活机台，液气激活息壤归入全局资源账；本表的伴随消耗不能当作独立激活入口的供给容量。</p>`}
 const e=Object.entries(res.count).filter(([k,v])=>v>1e-7).map(([k,v])=>[{upS:'赤铜固气上游',upL:'赤铜液气上游',furnace:'古法重息壤占用炉',envScorch:'灼铜共用酸性环境占用模块',heavy:'重息壤转固',heS:'赫铜固气末端',heL:'赫铜液气末端',scorchS:'灼铜固气末端',scorchL:'灼铜液气1末端',dragonS:'龙泡泡固气末端',dragonL:'龙泡泡液气末端'}[k]||res.customEquipment?.[k]?.name||k,fmt(v),res.customEquipment?.[k]?`${fmt(v*res.customEquipment[k].cost)}${res.customEquipment[k].resource===4?'息壤气':'息壤等价'}`:k==='furnace'?`${fmt(v*30)}息壤占用成本`:k.startsWith('env')?`${fmt(v*c.acidCost)}息壤占用成本`:k==='upL'?`${fmt(v*6)}液化息壤`:`${fmt(v*6)}息壤气`]);e.push(['息壤转气',fmt(res.nc),c.conversion==='S'?`${fmt(6*res.nc)}息壤气激活`:`${fmt(6*res.nc)}液化息壤激活`]);$('results').innerHTML+=`<h3>激活、占用与转气</h3>`+rowsTable(['设备组','启用数量或连续等价','激活/占用成本'],e)+`<p>转气主输入：${res.mode==='continuous'?fmt(res.B)+'息壤/min':take(res.B)}。${c.conversion==='S'?`净供气${fmt(res.B-6*res.nc)}/min`:`液化息壤激活${fmt(6*res.nc)}/min，供气${fmt(res.B)}/min`}。</p>`;
 if(res.mode!=='integer')$('results').innerHTML+=planTheoryHTML(res,c);
 $('results').innerHTML+=`<div class="capacity-note">${difference>=0?'产品价值足够消耗期望收购额度；超出的产品价值可能留在库存。':'产品价值不足以消耗全部期望收购额度。'}期望值不是每小时的保证值；目前仅比较期望，不报告售完概率。</div>`;
}

let worker;
function run(){if($('region').value==='valley'){render();return;}let c;try{c=cfg();if(c.mode==='continuous')for(const [k,mx] of Object.entries({splitters:50,mergers:50,limiters:30,storageBoxes:20,withdrawalPorts:20}))if(!Number.isInteger(c.budgets[k])||c.budgets[k]<0||c.budgets[k]>mx)throw Error('连续解器具上限必须为范围内的整数');validate(c)}catch(e){$('status').textContent=e.message;return}if(worker)worker.terminate();for(const id of ['exportExcel','exportPdf'])$(id).disabled=true;worker=new Worker('src/solver-worker.js');$('stage1Calculate').disabled=true;$('calculateTop').disabled=true;$('stage2Calculate').disabled=true;$('status').textContent=c.free?'正在计算两阶段自由计划…':c.calcGoal===2?'正在计算期望兑换…':'正在计算模式1…';worker.onmessage=e=>{$('stage1Calculate').disabled=false;$('calculateTop').disabled=false;$('stage2Calculate').disabled=false;if(!e.data.ok){$('status').textContent=e.data.error;return}modeSnapshots[c.calcGoal]={cfg:c,result:e.data.result};selectSnapshot();$('status').textContent='';$('exportStatus').textContent=c.free?'可导出固定计划、新增优先级、价值与资源账。':'可导出当前模式最近一次计算的输入与方案。';render();worker.terminate()};worker.onerror=()=>{$('stage1Calculate').disabled=false;$('calculateTop').disabled=false;$('stage2Calculate').disabled=false;$('status').textContent='计算失败，请调整输入后重试'};worker.postMessage(c)}
$('calculateTop').onclick=run;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=+b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('selected',x===b));render()});$('download').onclick=()=>{let html='<!doctype html>\n'+document.documentElement.outerHTML;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));a.download='终末地产线规划器.html';a.click()};
$('recipeBody').innerHTML=PRODUCTS.filter(p=>!p.bottle).map(p=>{let occupation=p.furnace?'30息壤/座（最多1满速）':p.environment?'1.2息壤/组（最多4满速）':'0';return `<tr><td>${p.name}</td><td>${p.route}</td><td>${p.out}</td><td>${p.raw.slice(0,3).join(' / ')}</td><td>${p.solidTotal}</td><td>${occupation}</td><td>${p.activationGas}</td><td>${p.activationLiquid}</td><td>${p.gasTotal}</td><td>${p.price}</td></tr>`}).join('');

try{document.modelContext?.registerTool({name:'calculate_production_plan',title:'计算终末地产线',description:'使用页面当前资源、工艺与模式，计算最大调度券与期望兑换的自用产物优先级方案。',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input)=>{if(input&&Object.keys(input).length)throw Error('此工具不接受额外输入');if($('region').value==='valley')throw Error('四号谷地计算暂未开放');run();return await new Promise((resolve,reject)=>{let old=worker.onmessage;worker.onmessage=e=>{old(e);if(e.data.ok)resolve({status:'complete',valuePerHour:last.result.first?.rev*60,priority:last.result.free?.priority});else reject(Error(e.data.error))}})},annotations:{readOnlyHint:false}})}catch{}
state();

$('mode').onchange=state;

for(const k of Object.keys(MIX_LIMITS)){const input=$('budget_'+k);input.oninput=()=>clampBudgetInput(input);input.onchange=()=>clampBudgetInput(input,true);input.onblur=()=>clampBudgetInput(input,true);}

function toggleTakeDetails(button){const open=button.getAttribute('aria-expanded')!=='true';button.closest('.take-details-group').querySelectorAll('details.take-detail').forEach(el=>el.open=open);button.setAttribute('aria-expanded',String(open));button.textContent=open?'收起全部接法':'展开全部接法';}
$('backToTop').onclick=()=>window.scrollTo({top:0,behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});

function selectSnapshot(){last=modeSnapshots[active]||null;for(const id of ['exportExcel','exportPdf'])$(id).disabled=!last;$('exportStatus').textContent=last?'导出当前模式最近一次计算结果。':'当前模式计算完成后可导出。';}
