// Shared by the browser and worker. All objectives use the same protected constraints.
function customValueFloor(c,q){if(q.policy==='theory')return 153600;if(q.policy==='expected')return c.threshold;if(q.policy==='stock')return Math.max(0,c.threshold*168-q.sales.filter(t=>!PRODUCTS.find(p=>p.name===t.name)?.activity||c.activity).reduce((n,t)=>n+(t.stock||0)*(unifiedPrice(t.name)||0),0))/168;return 0;}
function solveCustom(c){const q=c.questionnaire,entries=q.sales.filter(t=>!PRODUCTS.find(p=>p.name===t.name)?.activity||c.activity).map(t=>({name:t.name,route:'auto',stage:'sale',type:q.policy==='none'?'fixed':t.fine?t.type:'max',qty:q.policy==='none'?0:t.fine&&t.type==='fixed'?t.rate:0,min:t.fine&&t.type==='min'?t.rate:0,weight:t.weight}));for(const t of entries){const own=t.name==='中电'?c.power:t.name==='低电'?c.lowPower:0;if(t.type==='fixed')t.qty+=own;else t.min+=own;}for(const t of q.other){if(unifiedPrice(t.name)!==null)throw Error('第五步只填写非调度券产物，请在第四步设置：'+t.name);entries.push({...t,stage:'next',qty:t.type==='fixed'?t.fixed:0,min:t.type==='min'?t.min:0});}
const routes=entries.some(t=>unifiedAlias(t.name)==='赫铜瓶')?['bottleA','bottleS',...(c.liquid?['bottleL']:[])]:[null];let best=null;
for(const route of routes){const {m,vectors}=unifiedModel(c,entries,route);if(c.mode==='engineering'){for(let i=0;i<m.n;i++){const p=m.recipes[i];if(p.withdraw)continue;let coef=Math.max(...p.raw,p.reaction||0),offsets=[];if(p.node){coef=p.raw[3];const j=m.vars.indexOf('node_'+p.id);if(j>=0)offsets.push([j,-9.6]);}if(p.network){const input=p.sourceRecipe.inputs.find(x=>x.amount>0);if(input)coef=input.amount*60/p.sourceRecipe.seconds;}if(coef>0)expectGrid(m,i,coef,offsets);}expectGrid(m,m.conv,30);}
const gasUse=expectAddVariable(m,'customNaturalGas');expectRow(m,m.resource[4].map((v,i)=>[i,v]).concat([[gasUse,-1]]),0);
const expanded=vectors.map(v=>m.vars.map((_,i)=>v[i]||0));const sale=m.vars.map((_,i)=>entries.reduce((n,t,j)=>n+(t.stage==='sale'?(unifiedPrice(t.name)||0)*expanded[j][i]:0),0));const floor=customValueFloor(c,q)/60+powerCost(c);expectRow(m,sale.map((v,i)=>[i,-v]),-floor);
let s=null,exact=true;const scores=[];function optimize(obj,lock=true){m.obj=obj;const next=m.ints.length?mip(m,1500,s):lp(m.A,m.b,m.obj);if(!next)return false;s=next;exact&&=s.exact!==false;const v=obj.reduce((n,a,i)=>n+a*s.x[i],0);scores.push(v);if(lock)expectRow(m,obj.map((a,i)=>[i,-a]),-v+1e-6);return true;}
// Value first; minimum exchange policies reserve the remaining capacity for requested goods.
if(!optimize(sale.map(v=>q.policy==='all'?v:-v)))continue;
let ok=true;for(let j=0;j<entries.length;j++)if(entries[j].stage==='next'&&entries[j].type!=='fixed')if(!optimize(expanded[j])){ok=false;break;}if(!ok)continue;
for(const j of entries.map((_,j)=>j).filter(j=>entries[j].stage==='sale'&&entries[j].type!=='fixed'&&(entries[j].weight>0||entries[j].fine)).sort((a,b)=>entries[b].weight-entries[a].weight))if(!optimize(expanded[j])){ok=false;break;}if(!ok)continue;
const resourceKeys=['ore','blue','copper','solid','gas'];const chosen=resourceKeys.map((k,j)=>q.save.includes(k)?j:-1).filter(j=>j>=0);if(chosen.length&&!optimize(m.vars.map((_,i)=>-chosen.reduce((n,j)=>n+(j===4?(i===gasUse?1:0):m.resource[j][i])/Math.max(1,m.caps[j]),0))))continue;
optimize(m.vars.map((_,i)=>-m.resource.reduce((n,a,j)=>n+(j===4?(i===gasUse?1:0):a[i])/Math.max(1,m.caps[j]),0)),false);const p=unifiedPlan(c,m,s,entries,exact);p.customScores=scores;p.customFloor=customValueFloor(c,q);p.feasible=true;p.certificate=exact?'问卷约束已复核；依次优化兑换价值、非调度券优先级、调度券权重与资源节省。':'问卷约束已复核；搜索达到限制，返回可行候选，未证明全局最优。';if(!best||scores.some((v,i)=>Math.abs(v-best.customScores[i])>1e-5&&scores.slice(0,i).every((x,j)=>Math.abs(x-best.customScores[j])<=1e-5)&&v>best.customScores[i]))best=p;
}return best||{feasible:false,reason:'未找到满足问卷的方案。请检查产率、工艺开关、资源和整数／工程要求；搜索未完成也可能导致未找到候选。',resourceRows:[],outputs:[]};}
