// Inventory flow planning. Filled units consume one container and one content unit.
// Mode 4 retains sale permissions and resource inputs, and explicitly uses continuous rates.
function drainExtras(c){const extras=[],containers=[];const he=PRODUCTS.filter(p=>p.name==='赫铜'&&craftAllowed(p,c));for(let k=0;k<5;k++){if(k===3){for(const p of he){const r={...p,id:'drain_bottle_'+p.id,sourceId:'drain_bottle_'+p.id,name:'赫铜瓶',route:p.route.replace(/零件/g,'瓶'),price:0,out:30,raw:p.raw.map(v=>v*2),reaction:p.reaction*2,upCap:4,endCap:(p.endCap||0)*2,activationScale:2,expect:true,bottle:false,flowOutputs:{'@container_3':30},drainContainer:k};extras.push(r);containers.push(r);}}else{const r={id:'drain_container_'+k,name:DRAIN_CONTAINERS[k],route:'普通：'+(k===1?'蓝铁矿→致密蓝铁粉末→钢块→钢质瓶':k===0?'蓝铁矿→蓝铁块→蓝铁瓶':'赤铜矿→赤铜块→'+DRAIN_CONTAINERS[k]),price:0,out:30,raw:[0,k===0?60:k===1?120:0,k===2||k===4?60:0,0],reaction:0,expect:true,flowOutputs:{['@container_'+k]:30},drainContainer:k};extras.push(r);containers.push(r);}}
// Non-priced heavy xiranite feed is shared with the same activation and furnace groups as sales.
for(const p of PRODUCTS.filter(p=>p.name==='重息壤'&&craftAllowed(p,c))){const r={...p,id:'drain_feed_'+p.id,sourceId:p.id,price:0,raw:p.raw.slice(),expect:true,flowOutputs:{'重息壤':p.out}};if(p.id==='heavyA'){r.raw[3]=60;r.flowInputs={'壤晶废液':30};r.node=false;}extras.push(r);}
const ids=[34,35,103,114,115,116,118,122,123,124,125,130,131,132,134,135,136,141,142,144,145,146,147,150,151,152];const base={'源矿':0,'原矿':0,'蓝铁矿':1,'蓝铁粉末':1,'赤铜矿':2,'息壤':3,'液化息壤':3,'息壤气':4};const free=new Set(['清水','沉积酸','污水','惰气','芽针溶液','锦草溶液']);for(const n of ids){const r=DRAIN_RECIPE_PACKAGE.recipes.find(x=>x.id==='recipe_'+n);if(!r)throw Error('配方包缺少必要配方：'+n);const raw=[0,0,0,0],fi={},fo={};let reaction=0;for(const [list,sign,flow]of [[r.inputs,1,fi],[r.outputs,-1,fo]])for(const x of list){if(!(x.amount>0))continue;const value=x.amount*60/r.seconds;if(base[x.item]!==undefined){if(base[x.item]===4)reaction+=sign*value;else raw[base[x.item]]+=sign*value;}else if(!free.has(x.item)){const item=x.item==='赤铜耐压罐'?'@container_4':x.item;flow[item]=(flow[item]||0)+value;}}
const activation=r.catalystPerMinute?{key:'drain_activate_'+n,resource:r.catalyst==='息壤气'?4:3,cost:r.catalystPerMinute,name:r.machine+' · '+r.catalyst+'激活'}:undefined;extras.push({id:'drain_network_'+n,name:'加工 · '+r.outputs.map(x=>x.item).join('／'),route:r.machine,sourceRecipe:r,sourceId:r.id,network:true,price:0,out:r.outputs[0].amount*60/r.seconds,raw,reaction,expect:true,flowInputs:fi,flowOutputs:fo,customActivation:activation,...(r.environment==='酸性环境'?{environment:'envScorch',occupancyCapacity:4}:{} )});}
for(const t of DRAIN_TASKS.filter(t=>!t.empty)){const raw=[0,0,0,0],fi={['@container_'+t.k]:30};let reaction=0;if(t.item==='液化息壤')raw[3]=30;else if(t.item==='息壤气')reaction=30;else if(t.item)fi[t.item]=30;extras.push({id:t.id,name:t.name,route:'罐装：1空容器＋1'+t.content+'→1成品',out:30,raw,reaction,price:0,expect:true,withdraw:true,flowInputs:fi,drainTask:t.id});}
return extras;}
function drainModel(c,q,inventory,group=null,relaxSetup=false){const config={...c,mode:'continuous',free:false,power:c.power||0,lowPower:c.lowPower||0,expectTargets:[],expectExtras:drainExtras(c)};const m=build(config,2,null);m.recipes=m.recipes.map(p=>({...p,raw:p.raw.slice(),flowInputs:{...p.flowInputs},flowOutputs:{...p.flowOutputs}}));
// Mid batteries and ancient heavy use the same waste flow as bottled wastes.
for(let i=0;i<m.n;i++){const p=m.recipes[i];if(p.id==='mid'||p.id==='heavyA'){m.resource[3][i]=p.id==='mid'?0:60;p.flowInputs={'壤晶废液':p.id==='mid'?60:30};p.node=false;const node=m.vars.indexOf('node_'+p.id);if(node>=0)expectRow(m,[[node,1]],0);}}
const items=new Set;for(const p of m.recipes){Object.keys(p.flowInputs||{}).forEach(x=>items.add(x));Object.keys(p.flowOutputs||{}).forEach(x=>items.add(x));}for(const item of items){if(item.startsWith('@container'))continue;expectRow(m,m.recipes.map((p,i)=>[i,(p.flowInputs?.[item]||0)-(p.flowOutputs?.[item]||0)]),0);}
// Allocate external waste once between all sale and bottled-waste requirements.
if(wasteRate(c)>0){const j=expectAddVariable(m,'drain_externalWaste');expectRow(m,[[j,1]],wasteRate(c));const rowIndex=m.A.findIndex(a=>m.recipes.some((p,i)=>p.flowOutputs?.['壤晶废液']&&a[i]<0)&&m.recipes.some((p,i)=>p.flowInputs?.['壤晶废液']&&a[i]>0));if(rowIndex<0)throw Error('废液配平行缺失');m.A[rowIndex][j]=-1;const nodes=m.vars.map((name,i)=>name.startsWith('node_')?[i,12]:null).filter(Boolean);expectRow(m,nodes.concat([[j,1]]),wasteRate(c));}
const scale=Math.max(1,...DRAIN_TASKS.filter(t=>group===null||(typeof group==='number'?t.k===group:t.empty?t.k===group.k:group.ids.includes(t.id))).map(t=>Math.max(0,q.target-inventory[t.id])));const progress=expectAddVariable(m,'drain_progress');const vectors={};for(const t of DRAIN_TASKS){if(t.empty)continue;const v=m.vars.map((_,i)=>m.recipes[i]?.drainTask===t.id?30:0);vectors[t.id]=v;const demand=group===null||(typeof group==='number'?t.k===group:group.ids.includes(t.id))?Math.max(0,q.target-inventory[t.id]):0;const entries=v.map((n,i)=>[i,n]).concat([[progress,-demand/scale]]);expectRow(m,entries,0);expectRow(m,entries.map(([i,n])=>[i,-n]),0);}
for(let k=0;k<5;k++){const empty=DRAIN_TASKS.find(t=>t.k===k&&t.empty);const target=group===null||k===(typeof group==='number'?group:group.k)?q.target:0;const net=m.vars.map((_,i)=>(m.recipes[i]?.flowOutputs?.['@container_'+k]||0)-(m.recipes[i]?.flowInputs?.['@container_'+k]||0));vectors[empty.id]=net;expectRow(m,net.map((v,i)=>[i,-v]).concat([[progress,(target-inventory[empty.id])/scale]]),0);}
const packers=[];for(const t of DRAIN_TASKS.filter(t=>!t.empty)){const active=group===null||(typeof group==='number'?t.k===group:group.ids.includes(t.id));if(!active||inventory[t.id]>=q.target)continue;const i=m.recipes.findIndex(p=>p.drainTask===t.id),j=expectAddVariable(m,'drain_packer_'+t.id,true);expectRow(m,[[i,1],[j,-1]],0);if(!relaxSetup)expectRow(m,[[j,-1]],-1);packers.push([j,1]);}expectRow(m,packers,q.fillLimit);
expectRow(m,[[progress,1]],1000000);m.obj=m.vars.map((_,i)=>i===progress?1:0);return{m,progress,scale,vectors};}
function drainStage(c,q,inventory,group=null){const {m,progress,scale,vectors}=drainModel(c,q,inventory,group),root=lp(m.A,m.b,m.obj);if(!root||root.x[progress]<1e-8)return null;let s=m.ints.length?mip(m,1800):root;if(!s||s.x[progress]<1e-8)return null;const speed=s.x[progress];let duration=scale/speed;expectRow(m,[[progress,-1]],-speed*(1-1e-9));const gas=expectAddVariable(m,'drain_naturalGas');expectRow(m,m.resource[4].map((n,i)=>[i,n]).concat([[gas,-1]]),0);m.obj=m.vars.map((_,i)=>-(m.resource.slice(0,4).reduce((n,a,j)=>n+a[i]/Math.max(1,m.caps[j]),0)+(i===gas?1/Math.max(1,m.caps[4]):0)));const initial={x:s.x.concat(0)};initial.x[gas]=Math.max(0,m.resource[4].reduce((n,v,i)=>n+v*(initial.x[i]||0),0));const lean=m.ints.length?mip(m,500,initial):lp(m.A,m.b,m.obj);if(lean)s=lean;if(!validSolution(m,s))throw Error('罐装方案未通过资源复核');duration=scale/s.x[progress];const plan=planFromVector(m,s);plan.packerCount=m.vars.reduce((n,name,i)=>n+(name.startsWith('drain_packer_')?Math.round(s.x[i]):0),0);const rates=Object.fromEntries(DRAIN_TASKS.map(t=>[t.id,(vectors[t.id]||[]).reduce((n,v,i)=>n+v*s.x[i],0)]));const final=Object.fromEntries(DRAIN_TASKS.map(t=>[t.id,inventory[t.id]+duration*rates[t.id]]));if(DRAIN_TASKS.some(t=>final[t.id]<-0.01||((group===null||(t.empty?t.k===(typeof group==='number'?group:group.k):(typeof group==='number'?t.k===group:group.ids.includes(t.id))))&&final[t.id]<q.target-0.01)))throw Error('罐装库存守恒复核失败');const sales=plan.recipes.map((p,i)=>({name:p.name,route:p.route,rate:p.out*plan.r[i],price:p.price,value:p.price*p.out*plan.r[i]})).filter(t=>t.price>0&&t.rate>1e-6);if(plan.rev*60<c.threshold-0.01)throw Error('阶段调度券产值未达标');return{duration,lowerBound:scale/root.x[progress],exact:s.exact!==false,plan,rates,inventoryBefore:{...inventory},inventoryAfter:final,sales,group};}
function solveDrain(c){const progress=message=>{if(typeof DRAIN_PROGRESS==='function')DRAIN_PROGRESS(message);};progress('正在核算全部57种库存与资源下界…');const q=drainValidate(c.drain);if(c.region!=='wuling')throw Error('倒灌大师目前支持武陵');const completed=DRAIN_TASKS.every(t=>q.inventory[t.id]>=q.target);if(completed)return{feasible:true,minutes:0,lowerBound:0,stages:[],inventory:{...q.inventory},initialInventory:{...q.inventory},certificate:'全部57种库存已达到目标，无需继续罐装。',mode:'continuous'};
const cfg={...c,mode:'continuous',free:false,activity:false,products:c.products};let stages=[],candidate=null;const lowerModel=drainModel(cfg,q,q.inventory,null,true),lowerRoot=lp(lowerModel.m.A,lowerModel.m.b,lowerModel.m.obj);if(!lowerRoot||lowerRoot.x[lowerModel.progress]<1e-8)return{feasible:false,reason:'在当前资源、售卖工艺与期望额度下，没有找到能补齐全部库存的方案。请检查赫铜工艺是否全被关闭、所选商品能否达到期望、关键资源是否为0，或放宽灌装机上限。'};const lowerBound=lowerModel.scale/lowerRoot.x[lowerModel.progress];const balanced=drainStage(cfg,q,q.inventory);
if(q.schedule==='parallel'){if(!balanced)return{feasible:false,reason:'并行方案所需灌装机超过上限，或整数占用搜索未找到候选。请增加机台上限，或改用分批模式。'};stages=[balanced];candidate=balanced.duration;}else{const orders=[[3,4,1,2,0],[0,1,2,3,4],[4,3,2,1,0]];let best=null;for(const [orderIndex,order] of orders.entries()){progress('正在比较分批顺序 '+(orderIndex+1)+'/3…');let inventory={...q.inventory},parts=[],total=0,failed=false;for(const k of order){if(DRAIN_TASKS.filter(t=>t.k===k).every(t=>inventory[t.id]>=q.target))continue;const pending=DRAIN_TASKS.filter(t=>t.k===k&&!t.empty&&inventory[t.id]<q.target).map(t=>t.id);const chunks=[];for(let i=0;i<pending.length;i+=q.fillLimit)chunks.push(pending.slice(i,i+q.fillLimit));if(!chunks.length)chunks.push([]);for(const [chunkIndex,ids] of chunks.entries()){progress('顺序 '+(orderIndex+1)+'/3 · '+DRAIN_CONTAINERS[k]+' · 第'+(chunkIndex+1)+'/'+chunks.length+'组');const stage=drainStage(cfg,q,inventory,{k,ids});if(!stage){failed=true;break;}parts.push(stage);total+=stage.duration;inventory=stage.inventoryAfter;}if(failed)break;} // replenish any empty cans consumed for separation after their earlier stage.
if(!failed&&DRAIN_TASKS.some(t=>inventory[t.id]<q.target-0.01)){const tail=drainStage(cfg,q,inventory);if(tail){parts.push(tail);total+=tail.duration;inventory=tail.inventoryAfter;}else failed=true;}
if(!failed&&(!best||total<best.total))best={parts,total};}if(!best)return{feasible:false,reason:'未找到分批排程；并行方案可行，可改用并行优先或降低期望额度。'};stages=best.parts;candidate=best.total;}
let elapsed=0;for(const stage of stages){stage.start=elapsed;elapsed+=stage.duration;stage.end=elapsed;stage.plan.customEquipment=Object.fromEntries(stage.plan.recipes.filter(p=>p.customActivation).map(p=>[p.customActivation.key,p.customActivation]));}
return{feasible:true,minutes:elapsed,lowerBound,parallelMinutes:balanced?.duration??null,stages,inventory:stages.at(-1).inventoryAfter,initialInventory:{...q.inventory},gap:Math.max(0,elapsed/lowerBound-1),mode:'continuous',certificate:q.schedule==='batch'?'三种容器先后顺序中选取耗时最短的可行分批候选；没有穷尽所有换线排程。':'连续流量下的并行最短时间候选；包含古法阶梯和灼铜分段占用，未假定混合整数时间共享的全局最优。',modeNotice:c.mode!=='continuous'?'倒灌大师采用连续流量排程，左侧整数／工程模式未沿用；固定占用仍计入，实际器具接法需核对。':null};}
