// Every reported ordinary material has a feed plan. Companion feeds use backpressure;
// activation feeds must be exact. Pipe leftovers never go to a warehouse.
function ordinaryInputs(p,r,ns,res){
 if(p.withdraw)return [];
 if(p.network)return p.sourceRecipe.inputs.filter(x=>x.amount>0).map(x=>({material:x.item,v:x.amount*60/p.sourceRecipe.seconds*r,pipe:/气|液|水|酸/.test(x.item),note:'配方实际投入'}));
 const raw=productRaw(p,r,ns,res),rows=[];
 raw.forEach((v,i)=>{if(v<=1e-7)return;if((p.id==='mid'||p.sourceId==='mid')&&i===0){rows.push({material:'致密原石粉末',v:120*r,pipe:false,note:'实际粉末投入；原矿等价仅用于容量账。外运与本地粉末需分别接入'});const idx=res.recipes.findIndex(x=>x.id===p.id),prior=res.recipes.slice(0,idx).reduce((n,x,i)=>n+((x.id==='mid'||x.sourceId==='mid')?120*res.r[i]:0),0),external=Math.min(120*r,Math.max(0,(res.feedCfg?.powder||0)/60-prior));if(240*r-2*external>1e-7)rows.push({material:'原矿（本地致密粉末上游）',v:240*r-2*external,pipe:false,note:'另有外运粉末'+fmt(external,6)+'/min，粉末总需求'+fmt(120*r,6)+'/min；砂叶按无限供应口径'});return;}rows.push({material:['原矿','蓝铁','赤铜','息壤'][i],v,pipe:false});});
 if(p.reaction*r>1e-7)rows.push({material:'息壤气（反应）',v:p.reaction*r,pipe:true});return rows;
}
function pipeDirectTake(v){const whole=Math.floor((v+1e-7)/120),tail=Math.max(0,v-whole*120),limits=[];let n=tail;while(n>1e-7){const x=Math.min(60,n);limits.push(x);n-=x;}const exact=limits.every(x=>Math.abs(x/6-Math.round(x/6))<1e-6);const mergers=Math.ceil(Math.max(0,limits.length-1)/2);return {value:v,pipe:true,cap:120,whole,limits,splitters:0,mergers,limiters:limits.length,storageBoxes:0,withdrawalPorts:whole+limits.length,returnFlows:[],returnBranches:0,returnMergers:0,capacityOK:exact,cost:whole+limits.length*2+mergers,text:exact?[whole?whole+'条并行管道×120':'',...limits.map(x=>'管道支路直接限速'+fmt(x,6))].filter(Boolean).join('＋'):'未找到无余流的简单管道接法'};}
function exactFeedTake(v,pipe,mode,budgets){if(!pipe)return mode==='continuous'?mixedTake(v,false,budgets):engineeringTake(v,false);const t=pipeDirectTake(v);if(t.capacityOK)return t;const theory=mixedTake(v,true,budgets);return {...theory,capacityOK:false,fits:false,pipeUnresolved:true,text:'该精确流量需要主管配平；当前未证明其他支路可持续消耗余流，不能回仓，也不能仅将全部余流接回自身入口。建议人为构造或放弃该方案。'};}
function feedChoice(inputs,mode,budgets){const a=inputs.map((x,i)=>({i,take:exactFeedTake(x.v,x.pipe,mode,budgets)})).filter(x=>x.take.capacityOK!==false);return a.sort((a,b)=>(a.take.cost??Object.keys(MIX_LIMITS).reduce((n,k)=>n+a.take[k],0))-(b.take.cost??Object.keys(MIX_LIMITS).reduce((n,k)=>n+b.take[k],0)))[0]?.i??-1;}
function companionTake(v,pipe){if(pipe){const cap=Math.ceil((v-1e-7)/6)*6;return {...pipeDirectTake(cap),actual:v,supplyCapacity:cap,companion:true};}const cap=Math.ceil((v-1e-7)/30)*30;return {...engineeringTake(cap,false),actual:v,supplyCapacity:cap,companion:true};}
function feedText(t,mode){if(t.take.companion){const body=t.pipe?t.take.text:engineeringText(t.take.supplyCapacity,false);return body+'；供给容量'+fmt(t.take.supplyCapacity,6)+'/min，实际消耗'+fmt(t.v,6)+'/min。由'+t.bottleneck+'控速，回堵后入口只补充实际消耗，不取出多余流量'+(t.pipe?'；不回仓、不设流体储存':'')+'。';}if(t.take.pipeUnresolved)return t.take.text;if(t.pipe)return t.take.text+(t.take.activationOutlets?'；计'+t.take.splitters+'个管道分流器、'+t.take.activationOutlets+'个入口':'')+'（'+t.take.limiters+'管道限速器、'+t.take.mergers+'管道汇流器、0储物箱）'+(t.take.whole?'；各条120管道分送入口，禁止汇成超容量单管':'');return mode==='continuous'?mixedText(t.v,false,{...MIX_LIMITS,...t.budgets}):engineeringText(t.v,false);}
function mixedTargets(p,c){const rows=[],budgets={...MIX_LIMITS,...c?.budgets};p.recipes.forEach((r,i)=>{if(p.r[i]<1e-6)return;const inputs=ordinaryInputs(r,p.r[i],p.ns?.[i]||0,p),j=feedChoice(inputs,p.mode,budgets);inputs.forEach((x,k)=>rows.push({...x,name:r.name+' · '+r.route+' · '+x.material,kind:k===j?'控速原料':'伴随普通料',companion:k!==j&&j>=0,bottleneck:j>=0?inputs[j].material+' '+fmt(inputs[j].v,6)+'/min':'未找到精确控速原料'}));});
 if(p.B>1e-7){rows.push({name:'息壤转气主输入',material:'息壤',v:p.B,pipe:false,kind:'独立主输入'});if(c?.conversion==='L')rows.push({name:'液气转气 · 液化息壤主反应输入',material:'液化息壤',v:p.B,pipe:true,kind:'中间液体输入（已计入息壤主输入，不重复扣资源）'});}const waste=(p.ns||[]).reduce((n,v)=>n+12*v,0);if(waste>1e-7)rows.push({name:'中电等产线 · 外部息壤废液',material:'息壤废液',v:waste,pipe:true,kind:'节点废液（共享分配一次）'});
 for(const[k,n]of Object.entries(p.count||{})){if(n<1e-7)continue;if(k.startsWith('env'))rows.push({name:'环境固定成本 · 息壤',material:'息壤',v:(c?.acidCost??1.2)*n,pipe:false,kind:'固定占用'});else if(k==='furnace')rows.push({name:'古法炉固定占用 · 息壤',material:'息壤',v:30*n,pipe:false,kind:'固定占用'});else{const meta=p.customEquipment?.[k],liquid=k==='upL'||meta?.resource===3;rows.push({name:(meta?.name||activationNames[k]||'设备激活')+'供给（设备组总量）',material:liquid?'液化息壤':'息壤气',v:(meta?.cost??6)*n,pipe:true,kind:'激活（精确供给，不可回堵控速）'});}}
 if(p.nc>1e-7)rows.push({name:'息壤转气激活供给（设备组总量）',material:c?.conversion==='L'?'液化息壤':'息壤气',v:6*p.nc,pipe:true,kind:'激活（精确供给，不可回堵控速）'});return rows;
}
function mixedReport(p,c){p.feedCfg=c;const budgets={...MIX_LIMITS,...c?.budgets},engineering=p.mode!=='continuous',ts=mixedTargets(p,c).map(t=>({...t,budgets,take:t.companion?companionTake(t.v,t.pipe):exactFeedTake(t.v,t.pipe,p.mode,budgets)}));const q={ts,budgets,engineering,splitters:0,mergers:0,limiters:0,storageBoxes:0,withdrawalPorts:0,solidCounts:{splitters:0,mergers:0,limiters:0,withdrawalPorts:0},pipeCounts:{splitters:0,mergers:0,limiters:0,withdrawalPorts:0}},branches=[];
 for(const[i,t]of ts.entries()){if(t.kind.startsWith('激活')&&t.take.capacityOK){const outlets=Math.round(t.v/6);t.take={...t.take,splitters:Math.max(0,outlets-1),mergers:0,limiters:outlets,activationOutlets:outlets,text:'主管用管道分流树接出'+outlets+'条支路，每条独立管道限速6/min；逐条接激活入口，不共用反应气入口'};}const group=t.pipe?q.pipeCounts:q.solidCounts;for(const k of ['splitters','mergers','limiters','withdrawalPorts']){const v=(t.pipe&&k==='withdrawalPorts'?0:t.take[k])-(k==='mergers'?(t.take.returnMergers||0):0);q[k]+=v;group[k]+=v;}if(!t.pipe){for(const[j,flow]of(t.take.returnFlows||[]).entries())branches.push({id:`供料${i+1}支路${j+1}`,flow,material:t.material});if(t.take.core)for(const[j,x]of t.take.core.chunks.entries())if(x.category==='回仓')branches.push({id:`供料${i+1}支路${j+1}`,flow:x.flow,material:t.material});}}
 q.warehouse=warehousePlan(branches,engineering?20:budgets.storageBoxes,engineering?50:Math.max(0,budgets.mergers-q.mergers));q.storageBoxes=q.warehouse.boxes;q.returnMergers=q.warehouse.mergers;q.mergers+=q.returnMergers;q.solidCounts.mergers+=q.returnMergers;q.fits=q.warehouse.fits&&ts.every(t=>t.take.capacityOK!==false)&&(engineering||Object.keys(MIX_LIMITS).every(k=>q[k]<=budgets[k]));return q;
}
function allInputRows(p,r,ns,res){const inputs=ordinaryInputs(p,r,ns,res),budgets=res.budgets||MIX_LIMITS,j=feedChoice(inputs,res.mode,budgets);return inputs.map((x,k)=>{const t={...x,budgets,kind:k===j?'控速':'伴随',bottleneck:j>=0?inputs[j].material+' '+fmt(inputs[j].v,6)+'/min':'未找到',take:k!==j&&j>=0?companionTake(x.v,x.pipe):exactFeedTake(x.v,x.pipe,res.mode,budgets)};return x.material+' '+fmt(x.v,6)+'/min（'+(x.pipe?'管道':'传送带')+'）：'+feedText(t,res.mode)+(x.note?'；'+x.note:'');}).join('；\n')||'自用留存，不需另取原料';}
const previousControl=control;control=function(p,r,ns,res){res.feedCfg=res.feedCfg||last?.cfg;return allInputRows(p,r,ns,res);};
freeControl=control;
function planTheoryRows(p,c){const q=mixedReport(p,c);return [['全部原料取货；传送带＋管道器具合计'],['器具','分流器','汇流器','限速器','储物箱','取货口（物料）'],['上限',...Object.keys(MIX_LIMITS).map(k=>q.engineering?'不套用连续预算':q.budgets[k])],['本方案合计',...Object.keys(MIX_LIMITS).map(k=>q[k])],['物料器具',...['splitters','mergers','limiters'].map(k=>q.solidCounts[k]),q.storageBoxes,q.solidCounts.withdrawalPorts],['管道器具',...['splitters','mergers','limiters'].map(k=>q.pipeCounts[k]),0,q.pipeCounts.withdrawalPorts],['状态',q.fits?'所列供料候选符合要求':'供料未完整实现或超过器具预算：建议人为构造或放弃该方案'],...warehouseRows(q.warehouse),['供料对象','介质','实际消耗/min','供给容量/min','用途','接法'],...q.ts.map(t=>[t.name,t.pipe?'管道':'传送带',t.v,t.take.supplyCapacity??t.v,t.kind,feedText(t,p.mode)])];}
function planTheoryHTML(p,c){const q=mixedReport(p,c);let h='<h3>'+(q.engineering?'全部原料 · 工程取货方式':'混合分流 · 取货实现流程')+'</h3><p>所有普通原料、反应气、激活与固定占用均逐项列出。器具上限按物料与管道合计；管道供给支路不是仓库取货口。普通料选一个精确输入控速，其余入口给足容量、依靠回堵；供给容量不是新增资源消耗。激活必须精确供给。气液只走管道，容量120/min，管道限速为6—60、步长6。气液不储存、不回仓；反馈只能在配平、容量及其他支路去向明确时成立。没有去向的余流不算实现。</p>';
 h+=rowsTable(['器具','物料器具','管道器具','合计','连续解上限'],['splitters','mergers','limiters','withdrawalPorts'].map((k,i)=>[['分流器','汇流器','限速器','取货口（物料）'][i],q.solidCounts[k],q.pipeCounts[k],q[k],q.engineering?'—':q.budgets[k]]).concat([['储物箱',q.storageBoxes,0,q.storageBoxes,q.engineering?'—':q.budgets.storageBoxes]]));
 if(!q.fits)h+='<p class="negative"><strong>当前供料接法未完整实现或超过合计预算，建议人为构造或放弃该方案；下方仅供诊断。</strong></p>';
 h+=rowsTable(['原料供给对象','介质','实际消耗/min','供给容量/min','用途','取货方式'],q.ts.map(t=>[t.name,t.pipe?'管道':'传送带',fmt(t.v,6),fmt(t.take.supplyCapacity??t.v,6),t.kind,feedText(t,p.mode)]));
 h+='<div class="take-details-group"><button type="button" class="outline take-details-toggle" aria-expanded="false" onclick="toggleTakeDetails(this)">展开全部接法</button>'+warehouseHTML(q.warehouse);
 for(const t of q.ts){const k=t.take.core;h+='<details class="take-detail"><summary>'+escapeXML(t.name)+'：'+fmt(t.v,6)+'/min · '+(t.pipe?'管道':'传送带')+'</summary><p>'+feedText(t,p.mode)+'</p>';if(k?.chunks?.length)h+=rowsTable(['分流路径','用途','流量/min'],k.chunks.map(x=>[x.path,x.category,fmt(x.flow,6)]));h+='</details>';}
 return h+'</div>';
}
