let unifiedPhase=1;const planRows={fixed:[],next:[]};let baselineReady=false;
const planItems=[...new Set([...PRODUCTS.map(p=>p.name),...RECIPE_PACKAGE.recipes.flatMap(r=>r.outputs.filter(o=>o.amount>0).map(o=>o.item))])].sort((a,b)=>a.localeCompare(b,'zh-CN'));
function planCrafts(name){const alias=unifiedAlias(name);if(alias)return PRODUCTS.filter(p=>p.name===alias&&(!p.activity||$('activity').checked)&&(!p.id.endsWith('L')||$('liquid').value==='yes')).map(p=>({id:p.id,text:p.route}));return RECIPE_PACKAGE.recipes.filter(r=>r.inputs.length&&r.outputs.some(o=>o.item===name)&&(!(r.catalyst==='液化息壤')||$('liquid').value==='yes')&&($('activity').checked||!r.outputs.some(o=>o.item.includes('龙泡泡')))).map(r=>({id:r.id,text:r.machine+' · '+r.inputs.map(x=>x.item).join('＋')}));}
function refreshCrafts(kind,i){const name=$(`${kind}Item${i}`).value.trim(),select=$(`${kind}Route${i}`),old=select.value;select.innerHTML='<option value="auto">自动选择可用工艺</option>'+planCrafts(name).map(r=>`<option value="${escapeXML(r.id)}">${escapeXML(r.text)}</option>`).join('');select.value=[...select.options].some(o=>o.value===old)?old:'auto';}
function clearUnifiedResult(){baselineReady=false;$('nextPanel').hidden=true;$('baselineResult').innerHTML='';unifiedPhase=1;}
function invalidateFixed(){clearUnifiedResult();delete modeSnapshots[2];if(active===2){selectSnapshot();$('results').innerHTML='<div class="empty">固定计划已修改，请先重新核算剩余资源。</div>';}}
function addPlanRow(kind){const i=(planRows[kind].length?Math.max(...planRows[kind])+1:0),div=document.createElement('div');div.className='plan-item';div.id=kind+'Row'+i;div.innerHTML=`<h3>${kind==='fixed'?'固定产物':'优先级'} ${i+1}<button type="button" class="outline delete-row" id="${kind}Delete${i}" aria-label="删除本行">删除</button></h3><label class="field">制作物品<input id="${kind}Item${i}" type="search" autocomplete="off" placeholder="搜索名称，例如：电池、灼铜、零件" aria-controls="${kind}Suggest${i}"></label><div id="${kind}Suggest${i}" class="expect-suggestions" hidden></div><label class="field">工艺<select id="${kind}Route${i}"><option value="auto">自动选择可用工艺</option></select></label>`+(kind==='fixed'?`<label class="field">固定产率/min<input id="fixedQty${i}" type="number" min="0" max="10000" step="any" value="0"></label>`:`<div class="choice-grid"><div class="choice-cell"><label><input id="nextMinChoice${i}" name="nextRequirement${i}" type="radio" value="min">最低产率/min</label><input id="nextMin${i}" type="number" min="0" max="10000" step="any" value="0" aria-label="优先级${i+1}最低产率"></div><div class="choice-cell"><label><input id="nextFixedChoice${i}" name="nextRequirement${i}" type="radio" value="fixed">固定产率/min</label><input id="nextFixed${i}" type="number" min="0" max="10000" step="any" value="0" aria-label="优先级${i+1}固定产率"></div><div class="choice-cell"><label><input id="nextMaxChoice${i}" name="nextRequirement${i}" type="radio" value="max" checked>最大化</label><p class="hint">使用前面优先项满足后剩余的资源。</p></div></div>`);$(kind==='fixed'?'fixedRows':'nextRows').appendChild(div);planRows[kind].push(i);renumberPlanRows(kind);$(`${kind}Delete${i}`).onclick=()=>{div.remove();planRows[kind].splice(planRows[kind].indexOf(i),1);renumberPlanRows(kind);if(kind==='fixed')invalidateFixed();};
 const input=$(`${kind}Item${i}`),list=$(`${kind}Suggest${i}`);const show=()=>{const q=input.value.trim();const names=planItems.filter(n=>n.includes(q));list.innerHTML=names.length?names.map(n=>`<button type="button" data-name="${escapeXML(n)}">${escapeXML(n)}</button>`).join(''):'<p>没有匹配的物品</p>';list.hidden=false;};input.onfocus=show;input.oninput=()=>{show();refreshCrafts(kind,i);if(kind==='fixed')invalidateFixed();};input.onkeydown=e=>{if(e.key==='Escape')list.hidden=true;};input.onblur=()=>setTimeout(()=>list.hidden=true,180);list.onmousedown=e=>e.preventDefault();list.onclick=e=>{const b=e.target.closest('button[data-name]');if(!b)return;input.value=b.dataset.name;list.hidden=true;refreshCrafts(kind,i);if(kind==='fixed')invalidateFixed();};$(`${kind}Route${i}`).onchange=()=>{if(kind==='fixed')invalidateFixed();};
 if(kind==='fixed')$('fixedQty'+i).oninput=invalidateFixed;else{const choose=type=>{for(const [t,id]of [['min','Min'],['fixed','Fixed'],['max','Max']])$('next'+id+'Choice'+i).checked=t===type;if(type!=='min')$('nextMin'+i).value=0;if(type!=='fixed')$('nextFixed'+i).value=0;};$('nextMin'+i).oninput=()=>choose('min');$('nextFixed'+i).oninput=()=>choose('fixed');for(const[type,id]of [['min','Min'],['fixed','Fixed'],['max','Max']])$('next'+id+'Choice'+i).onchange=()=>choose(type);}}
function readPlanRows(kind){const rows=[];for(const i of planRows[kind]){const name=$(`${kind}Item${i}`).value.trim(),route=$(`${kind}Route${i}`).value||'auto';const type=kind==='fixed'?'fixed':$('nextFixedChoice'+i).checked?'fixed':$('nextMinChoice'+i).checked?'min':'max';const qty=kind==='fixed'?+$('fixedQty'+i).value:0,min=kind==='next'?+$('nextMin'+i).value:0,fixed=kind==='next'?+$('nextFixed'+i).value:0;if(!name){if(qty>0||min>0||fixed>0)throw Error('请为'+(i+1)+'行填写的产率选择物品');continue;}if(!planItems.includes(name))throw Error('请从物品候选中选择：'+name);if(route!=='auto'&&!planCrafts(name).some(r=>r.id===route))throw Error(name+'的工艺不符合当前工艺或活动权限');for(const n of [qty,min,fixed])if(!Number.isFinite(n)||n<0||n>10000)throw Error('产率应为0至10000的有限数值');rows.push({name,route,qty,min:type==='min'?min:0,fixed:type==='fixed'?fixed:0,type});}return rows;}
function moneyHTML(p,c,title='计划调度券价值'){const value=p.rev*60,delta=value-c.threshold;if(!Number.isFinite(value))return '';return `<div class="money-card"><label>${title}（扣供电）</label><p><strong>${fmt(value,2)} 价值/h</strong> · ${fmt(p.rev,4)}/min</p><p class="${delta>=-1e-5?'positive':'negative'}">相对期望 ${fmt(c.threshold,2)}/h：${delta>=0?'+':''}${fmt(Math.abs(delta)<1e-5?0:delta,2)}/h</p><p class="hint">仅计已提供售价的最终产物；中间加工品不重复计价。期望值用于对比，不是自由模式的硬性生产要求。</p></div>`;}
function outputRows(p){return (p.outputs||[]).map(t=>[t.stage==='fixed'?'原固定计划':t.stage==='power'?'供电自动补足':'新增优先级',t.name,t.route==='auto'?'自动':t.route,fmt(t.rate,6),t.type==='fixed'?'固定 '+fmt(t.qty):t.type==='min'?'最低 '+fmt(t.min):'最大化',t.price===null?'未计价':fmt(t.rate*t.price,4)]);}
function renderFree(){const p=last?.result?.free,c=last?.cfg;if(!p){$('results').innerHTML='<div class="empty">先填写当前计划，核算后安排新增产物。</div>';return;}const base=p.baseline||p;baselineReady=base.feasible;$('nextPanel').hidden=!baselineReady;$('baselineResult').innerHTML='<h3>第一步 · 固定计划资源账</h3>'+moneyHTML(base,c,'固定计划调度券价值')+rowsTable(['基础资源','容量/min','实际使用/min','剩余/min','缺口/min'],(base.resourceRows||[]).map(r=>[r.name,fmt(r.capacity),fmt(r.used),fmt(r.remaining),fmt(r.shortage)]));if((base.gasSurplus||0)>1e-7)$('baselineResult').innerHTML+='<p>自产息壤气富余 '+fmt(base.gasSurplus)+'/min；单独列示，不计入天然气剩余。</p>';let h=`<h2 class="${p.feasible?'positive':'negative'}">${p.phase===2?'两阶段总计划':'固定计划'} · ${p.feasible?'资源可实现':'未找到可行方案'}</h2><p>${escapeXML(p.feasible?p.certificate:p.reason||'检查工艺与产率。')}</p>`;if(Number.isFinite(p.rev))h+=moneyHTML(p,c);h+=rowsTable(['计划类别','物品','选择工艺','产率/min','要求','毛价值/min（未扣供电）'],outputRows(p));h+='<p class="hint">供电扣除：中电 '+fmt(c.power)+'×54 ＋低电 '+fmt(c.lowPower||0)+'×25 价值/min。未提供售价的物品不计入调度券。</p>';h+=rowsTable(['基础资源','容量/min','实际使用/min','剩余/min','缺口/min'],(p.resourceRows||[]).map(r=>[r.name,fmt(r.capacity),fmt(r.used),fmt(r.remaining),fmt(r.shortage)]));if((p.gasSurplus||0)>1e-7)h+='<p>自产息壤气富余 '+fmt(p.gasSurplus)+'/min；天然气实际取用为0。气体不能回仓，需减少产气或安排消耗。</p>';if(p.feasible&&p.recipes){p.budgets=c.budgets;p.feedCfg=c;h+='<h3>实际生产工艺与中间加工</h3>'+rowsTable(['产物／加工','工艺','产率/min','等价满速'],p.recipes.map((r,i)=>p.r[i]>1e-6?[r.name,r.route,fmt(r.out*p.r[i],6),fmt(p.r[i],6)]:null).filter(Boolean));h+=planTheoryHTML(p,c);if(p.phase===2)h+='<p class="hint">第二步在保留固定产率和指定工艺的前提下统一重算共享设备。自动工艺可能改变，因此最终资源账以本次总计划为准；第一步剩余量是核算参考。</p>';}else $('nextPanel').hidden=!base.feasible;$('results').innerHTML=h;}
function freeExportSheets(snapshot){const c=snapshot.cfg,p=snapshot.result.free,base=p.baseline||p;return [{name:'自由模式输入',rows:[['两阶段自由模式'],['解模式',reportMode[c.mode]],['期望价值/h',c.threshold],...['ore','blue','copper','solid','gas','powder','blueTransport','waste','acidCost','conversion','liquid'].map(k=>[k,c[k]]),['供电中电/min',c.power],['供电低电/min',c.lowPower||0],['预算','分流器','汇流器','限速器','储物箱','取货口'],['上限',...Object.keys(MIX_LIMITS).map(k=>c.budgets[k])],[],['第一步','物品','工艺','固定产率/min'],...(c.fixedTargets||[]).map((t,i)=>[i+1,t.name,t.route,t.qty]),[],['第二步优先级','物品','工艺','要求','最低产率','固定产率'],...(c.nextTargets||[]).map((t,i)=>[i+1,t.name,t.route,t.type,t.min,t.fixed])]},{name:'固定计划资源',rows:[['自产息壤气富余/min',base.gasSurplus||0],['扣供电价值/h',base.rev*60],['相对期望/h',base.rev*60-c.threshold],['基础资源','容量','使用','剩余','缺口'],...(base.resourceRows||[]).map(r=>[r.name,r.capacity,r.used,r.remaining,r.shortage])]},{name:'总计划与价值',rows:[['状态',p.feasible?'资源可实现':p.reason],['自产息壤气富余/min',p.gasSurplus||0],['扣供电价值/h',p.rev*60],['相对期望/h',p.rev*60-c.threshold],['计划类别','物品','选择工艺','产率/min','要求','毛价值/min'],...outputRows(p),[],['基础资源','容量','使用','剩余','缺口'],...(p.resourceRows||[]).map(r=>[r.name,r.capacity,r.used,r.remaining,r.shortage]),...(p.feasible&&p.recipes?planTheoryRows(p,c):[])]}];}
$('addFixed').onclick=()=>addPlanRow('fixed');$('addNext').onclick=()=>addPlanRow('next');for(let i=0;i<2;i++){addPlanRow('fixed');addPlanRow('next');}
$('stage1Calculate').onclick=()=>{unifiedPhase=1;run();};$('stage2Calculate').onclick=()=>{if(!baselineReady){$('status').textContent='请先核算第一步固定计划。';return;}unifiedPhase=2;run();};
function unifiedState(){$('unifiedPanel').hidden=active!==2;$('freeMode').checked=active===2;$('calculateTop').hidden=active!==1;selectSnapshot();render();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=+b.dataset.tab;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('selected',t===b));unifiedState();});
const baseState=state;state=function(){baseState();for(const kind of ['fixed','next'])for(const i of planRows[kind])refreshCrafts(kind,i);};$('current').onchange=state;$('node').onchange=state;$('useMidPower').onchange=state;$('useLowPower').onchange=state;$('transport').onchange=state;$('transportAmount').oninput=state;$('mode').onchange=state;$('activity').onchange=state;$('engineerPreset').onchange=()=>{if($('engineerPreset').checked)$('extremePreset').checked=false;state();};$('extremePreset').onchange=()=>{if($('extremePreset').checked)$('engineerPreset').checked=false;state();};state();
// Remove generated form rows before serializing so the offline copy initializes once.
$('download').onclick=()=>{const root=document.documentElement.cloneNode(true);for(const id of ['fixedRows','nextRows','baselineResult','results'])root.querySelector('#'+id).innerHTML='';root.querySelector('#unifiedPanel').hidden=true;root.querySelector('#nextPanel').hidden=true;root.querySelector('#calculateTop').hidden=false;root.querySelectorAll('.tab').forEach(t=>t.classList.toggle('selected',t.dataset.tab==='1'));for(const id of ['stage1Calculate','stage2Calculate','calculateTop'])root.querySelector('#'+id).disabled=false;for(const id of ['exportExcel','exportPdf'])root.querySelector('#'+id).disabled=true;root.querySelector('#status').textContent='';saveBlob(new Blob(['<!doctype html>\n'+root.outerHTML],{type:'text/html;charset=utf-8'}),'终末地产线规划器.html');};

function renumberPlanRows(kind){planRows[kind].forEach((i,n)=>{const h=$(kind+'Row'+i)?.querySelector?.('h3');if(h?.firstChild)h.firstChild.textContent=(kind==='fixed'?'固定产物 ':'优先级 ')+(n+1);});}
