// Step quantities use original single-step recipes; sale coefficients are unchanged.
const PROCESS_ACTIVITY=[{"id":"flow_activity_xiranite_lung","seconds":10,"machine":"封装机","inputs":[{"item":"实验龙泡泡外壳","amount":5},{"item":"实验铜骨骼","amount":5}],"outputs":[{"item":"息壤龙泡泡","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_xiranite_enr_lung","seconds":10,"machine":"封装机","inputs":[{"item":"实验龙泡泡重壳","amount":1},{"item":"实验息壤铜骨骼","amount":1}],"outputs":[{"item":"重息壤龙泡泡","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_xiranite_nugget","seconds":2,"machine":"精炼炉","inputs":[{"item":"息壤","amount":1}],"outputs":[{"item":"实验息壤块","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_xiranite_box","seconds":2,"machine":"塑形机","inputs":[{"item":"实验息壤块","amount":1}],"outputs":[{"item":"实验龙泡泡外壳","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_copper_xiranite_tool","seconds":2,"machine":"封装机","inputs":[{"item":"赤铜零件","amount":4},{"item":"息壤","amount":1}],"outputs":[{"item":"实验铜骨骼","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_copper_poly_gas","seconds":2,"machine":"气体反应炉","inputs":[{"item":"气态赤铜","amount":2},{"item":"息壤气","amount":1}],"outputs":[{"item":"实验息壤铜气","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_phase_trans_2-activity_copper_poly_gas","seconds":2,"machine":"固气转化机","inputs":[{"item":"实验息壤铜锭","amount":1}],"outputs":[{"item":"实验息壤铜气","amount":1}],"catalyst":"息壤气","catalystPerMinute":6},{"id":"flow_phase_trans_2-activity_copper_poly","seconds":2,"machine":"固气转化机","inputs":[{"item":"实验息壤铜气","amount":1}],"outputs":[{"item":"实验息壤铜锭","amount":1}],"catalyst":"息壤气","catalystPerMinute":6},{"id":"flow_activity_copper_poly_cmpt","seconds":10,"machine":"配件机","inputs":[{"item":"实验息壤铜锭","amount":5}],"outputs":[{"item":"实验息壤铜零件","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_xiranite_enr_nugget","seconds":10,"machine":"精炼炉","inputs":[{"item":"重息壤","amount":1}],"outputs":[{"item":"实验重息壤块","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_copper_poly_tool","seconds":10,"machine":"封装机","inputs":[{"item":"实验息壤铜零件","amount":1},{"item":"重息壤","amount":1}],"outputs":[{"item":"实验息壤铜骨骼","amount":1}],"catalyst":null,"catalystPerMinute":0},{"id":"flow_activity_xiranite_enr_box","seconds":10,"machine":"塑形机","inputs":[{"item":"实验重息壤块","amount":1},{"item":"惰气","amount":5}],"outputs":[{"item":"实验龙泡泡重壳","amount":1}],"catalyst":null,"catalystPerMinute":0}];
function balancedProductionSteps(id,rate,wasteSupply=0){
 const catalog=RECIPE_PACKAGE.recipes.concat(PROCESS_ACTIVITY),lookup=new Map(catalog.map(r=>[r.id,r])),steps=new Map(),errors=[];
 const pick={'源石粉末':'recipe_38','致密源石粉末':'recipe_106','砂叶粉末':'recipe_43','蓝铁块':'recipe_9','蓝铁粉末':'recipe_36','铁制零件':'recipe_47','赤铜块':'recipe_34','赤铜粉末':'recipe_35','赤铜零件':'recipe_51','蓝铁瓶':'recipe_54','赤铜瓶':'recipe_58','芽针粉末':'recipe_46','芽针溶液':'recipe_111','蓝铁瓶（装有芽针溶液）':'recipe_89','赤铜瓶（装有芽针溶液）':'recipe_91','赤铜溶液':'recipe_115','赤铜耐压罐':'recipe_60','分离芯':'recipe_103','气态赤铜':'recipe_145','气态赫铜':'recipe_125','赫铜块':'recipe_151','气态灼铜':'recipe_130','灼铜块':'recipe_152','重息壤气':'recipe_124','重息壤':'recipe_149','液化息壤':'recipe_113'};
 const liquidUp=['heL','heHybridL','scorchL','dragonL','bottleL'];if(liquidUp.includes(id))pick['气态赤铜']='recipe_135';
 if(['heA','bottleA','heHybridL','scorchHybridS'].includes(id))pick['赫铜块']='recipe_118';
 if(['heA','bottleA','heHybridS','scorch2L','scorchHybridS'].includes(id))pick['赫铜溶液']='recipe_123';
 if(['heHybridS','scorch2L'].includes(id))pick['气态赫铜']='recipe_136';
 if(id==='heHybridL')pick['赫铜溶液']='recipe_142';
 if(id==='scorchHybridS')pick['气态赫铜']='recipe_146';
 if(id==='heavyL')pick['息壤气']='recipe_133';
 for(const r of PROCESS_ACTIVITY)if(!r.id.startsWith('flow_phase_trans'))for(const x of r.outputs)pick[x.item]=r.id;
 pick['实验息壤铜锭']='flow_phase_trans_2-activity_copper_poly';
 function cycles(r,f){if(!r||!(f>1e-9))return;const old=steps.get(r.id);if(old)old.cycles+=f;else steps.set(r.id,{recipe:r,cycles:f});}
 function demand(item,qty,path=new Set()){
  const key=pick[item];if(!key||qty<1e-9)return;if(path.has(key)){errors.push('循环步骤需按资源账配平：'+item);return;}const r=lookup.get(key),out=r?.outputs.find(o=>o.item===item);if(!r||!out?.amount){errors.push('未找到单步配方：'+item);return;}const f=qty/out.amount,next=new Set(path).add(key);for(const x of r.inputs)demand(x.item,x.amount*f,next);cycles(r,f);
 }
 const finals={low:['recipe_101','低容武陵电池'],blue:['recipe_97','芽针针剂'],purple:['recipe_98','优质芽针针剂'],heA:['recipe_52','赫铜零件'],heS:['recipe_52','赫铜零件'],heL:['recipe_52','赫铜零件'],heHybridS:['recipe_52','赫铜零件'],heHybridL:['recipe_52','赫铜零件'],scorchS:['recipe_53','灼铜零件'],scorchL:['recipe_53','灼铜零件'],scorch2L:['recipe_53','灼铜零件'],scorchHybridS:['recipe_53','灼铜零件'],heavyS:['recipe_149','重息壤'],heavyL:['recipe_149','重息壤'],bottleA:['recipe_59','赫铜瓶'],bottleS:['recipe_59','赫铜瓶'],bottleL:['recipe_59','赫铜瓶'],bubble:['flow_activity_xiranite_lung','息壤龙泡泡'],dragonS:['flow_activity_xiranite_enr_lung','重息壤龙泡泡'],dragonL:['flow_activity_xiranite_enr_lung','重息壤龙泡泡']};
 if(id==='mid'||id==='heavyA'){
  const line=rate/6,need=(id==='mid'?60:30)*line,external=Math.min(need,Math.max(0,wasteSupply)),liquid=(need-external)/1.25;
  demand('液化息壤',liquid);cycles(lookup.get('recipe_116'),liquid);cycles(lookup.get('recipe_122'),liquid/4);
  if(external>1e-9)steps.set('external_waste',{external,recipe:{id:'external_waste',machine:'外部废液分配',inputs:[],outputs:[{item:'壤晶废液',amount:external}]},cycles:1});
  if(id==='mid'){demand('蓝铁粉末',30*line);cycles(lookup.get('recipe_117'),30*line);demand('致密源石粉末',120*line);cycles(lookup.get('recipe_102'),rate);}else cycles(lookup.get('recipe_121'),rate);
 }else{const final=finals[id];if(final){pick[final[1]]=final[0];demand(final[1],rate);}else errors.push('未绑定此工艺的单步流程。');}
 return {steps:[...steps.values()],errors};
}
function stepAmountText(items,cycles){return items.map(x=>fmt(x.amount*cycles,6)+' '+x.item).join(' ＋ ')||'无';}
function productionBalanceHTML(r,id,rate,plan){
 const index=plan?.recipes?.indexOf(r),waste=index>=0?12*(plan.ns?.[index]||0):0,result=balancedProductionSteps(id,rate,waste);
 if(!result.steps.length)return '<p>此流程暂缺完整单步数据，不能给出未经核对的数量。</p>';
 const mode=last?.cfg?.mode||'continuous';return '<h4>逐步数量配平 · /min</h4><p>'+(plan?'按本次实际产率':'参考：按一条满速产线')+' '+fmt(rate,6)+'/min 计算。清水、污水、酸和植物辅料同时列出；副产物保留。步骤的激活入口另列，共享设备以主报告统一资源账为准，不将逐步激活列再次加到总账。外部运输替代的原矿段显示配方等价需求，实际自产量见资源账。</p>'+detailTable(['步骤／设备','普通原料输入/min → 全部输出/min','实际负荷／满速等价','另需激活供给/min'],result.steps.map(x=>{
 const machine=x.cycles*x.recipe.seconds/60,activation=x.recipe.catalystPerMinute||0;return [x.recipe.machine,stepAmountText(x.recipe.inputs,x.cycles)+' → '+stepAmountText(x.recipe.outputs,x.cycles),x.external?'外部分配':fmt(machine,6),activation?fmt(activation*(mode==='continuous'?machine:Math.ceil(machine-1e-8)),6)+' '+x.recipe.catalyst:'无'];
 }))+result.errors.map(e=>'<p>'+escapeXML(e)+'</p>').join('');
}
