/* Chinese craft labels, explicit power accounting, and complete recipe reference. */
function craftName(name,id,plan){if(id==='auto')return '自动选择';if(id==='withdraw')return '自用留存';const r=PRODUCTS.find(r=>r.id===id||r.sourceId===id)||(plan?.recipes||[]).find(r=>r.id===id||r.sourceId===id);if(r)return r.route;const q=RECIPE_PACKAGE.recipes.find(r=>r.id===id);return q?q.machine:'工艺资料待核对';}
function powerCaption(c){return c.power>0||c.lowPower>0?'（已扣勾选供电自用）':'（未扣供电）';}
function powerNotice(c){return '<p class="power-notice">'+(c.power>0||c.lowPower>0?'本次仅扣除勾选的供电自用：中电 '+fmt(c.power||0)+'/min，低电 '+fmt(c.lowPower||0)+'/min；未勾选的电池不扣除。':'未勾选电池消耗：本次售卖价值未扣除供电电池，请确认实际供电需求。')+'</p>';}
function detailTable(head,rows){return rowsTable(head,rows.map(row=>row.map(x=>escapeXML(String(x??'')))));}
function recipeRateText(items,factor){return items.map(x=>x.item+' '+fmt(x.amount*factor,6)+'/min').join('；')||'无';}
function detailCurrentPlan(){const result=last?.result;return result?.free||result?.first||result;}
function productionDetailsHTML(term=''){
const plan=detailCurrentPlan(), c=last?.cfg, text=term.trim();let html='<p>输入关键字查看产物及全部上游配方。单机表按满速每分钟配平；当前方案表按实际产率配平。激活、占用和共享设备成本以计算结果资源账为准，不能重复相加。</p>';
if(plan?.recipes){const rows=[];plan.recipes.forEach((r,i)=>{const n=plan.r[i];if(!(n>1e-7)||text&&!r.name.includes(text))return;const raw=productRaw(r,n,plan.ns?.[i]||0,plan);const ins=r.sourceRecipe?recipeRateText(r.sourceRecipe.inputs,60/r.sourceRecipe.seconds*n):['原矿','蓝铁矿','赤铜矿','息壤'].map((name,j)=>raw[j]>1e-8?name+' '+fmt(raw[j],6)+'/min':'').filter(Boolean).join('；');const outs=r.sourceRecipe?recipeRateText(r.sourceRecipe.outputs,60/r.sourceRecipe.seconds*n):r.name+' '+fmt(r.out*n,6)+'/min';rows.push([r.name,r.route,ins||'无',outs,r.sourceRecipe?'实际中间加工步骤':'整线配平（不含另列的转气、激活与占用）']);});html+='<h3>当前计算方案 · 实际配平</h3>'+detailTable(['产物／中间加工','工艺','原料输入','产物输出','范围'],rows);if(c)html+=powerNotice(c);html+='<p>整线配方没有单机路线数据时，不推测中间步骤。下方完整配方是可用资料，未必全部用于当前方案。完整资源及转气、激活成本仍见主报告。</p>';}
html+='<h3>整线工艺配料表 · 每条满速</h3>'+detailTable(['产物','工艺','原矿','蓝铁矿','赤铜矿','息壤总','息壤气总','占用','激活气','激活液化息壤','单价','产量/min'],RECIPE_PACKAGE.planningCoefficients.filter(r=>!text||String(r[0]).includes(text)).map(r=>r.slice(0,12)));
const recipes=RECIPE_PACKAGE.recipes;let selected=recipes;
if(text){const names=new Set([text]),ids=new Set();let frontier=[text];for(let k=0;k<30&&frontier.length;k++){const next=[];for(const r of recipes){if(r.outputs.some(o=>frontier.some(n=>o.item.includes(n)))){ids.add(r.id);for(const x of r.inputs){if(!names.has(x.item)){names.add(x.item);next.push(x.item);}}}}frontier=next;}selected=recipes.filter(r=>ids.has(r.id));}
html+='<h3>完整配方资料 · 单机满速与上游全部候选</h3>'+detailTable(['产物','设备／配方','周期/s','原料/min','输出/min','激活／环境'],selected.map(r=>[r.outputs.map(o=>o.item).join('、'),r.machine, r.seconds,recipeRateText(r.inputs,60/r.seconds),recipeRateText(r.outputs,60/r.seconds),[r.catalyst?JSON.stringify(r.catalyst):'',r.catalystPerMinute?'激活供给 '+JSON.stringify(r.catalystPerMinute)+'/min':'',r.environment||''].filter(Boolean).join('；')]));
html+='<details><summary>上传 JSON 示例的完整节点配平（不是当前计算结果）</summary><div id="flowReferenceBody">展开后读取示例配方。</div></details>';return html;}
async function loadFlowReference(){const target=$('flowReferenceBody');if(!target)return;try{const res=await fetch('src/flow-reference.json');if(!res.ok)throw Error('读取失败');const data=await res.json();const rows=data.nodes.filter(n=>n.recipe).map(n=>{const incoming=data.links.filter(l=>String(l.target?.id??l.target)===String(n.id));const outgoing=data.links.filter(l=>String(l.source?.id??l.source)===String(n.id));const labels=a=>a.map(l=>l.name+' '+l.text).join('；')||'无';return [n.name,labels(incoming),labels(outgoing),JSON.stringify(n.recipe.in),JSON.stringify(n.recipe.out)];});target.innerHTML=detailTable(['示例节点','输入实际流量','输出实际流量','原始输入配方','原始输出配方'],rows);}catch(e){target.textContent='示例暂时无法读取；完整配方资料仍可查阅。请通过网页服务器打开文件。';}}
function openProductionDetails(name=''){const body=$('productionDetailsBody');body.innerHTML='<label>搜索产物或中间物品 <input id="productionDetailSearch" type="search" placeholder="例如：分离芯、重息壤"></label><div id="productionDetailTables"></div>';$('productionDetailSearch').value=name;const refresh=()=>{$('productionDetailTables').innerHTML=productionDetailsHTML($('productionDetailSearch').value);loadFlowReference();};$('productionDetailSearch').oninput=refresh;refresh();$('productionDetailsDialog').showModal();}
$('productionDetailsOpen').onclick=()=>openProductionDetails();$('productionDetailsClose').onclick=()=>$('productionDetailsDialog').close();
const detailBaseRender=render;render=function(){detailBaseRender();if(last?.result&&!last.error){for(const name of new Set((detailCurrentPlan()?.recipes||[]).map(r=>r.name))){const plain='<td>'+escapeXML(name)+'</td>';const link='<td><a href="#production-details" class="production-detail-link" onclick="openProductionDetails('+escapeXML(JSON.stringify(name))+');return false">'+escapeXML(name)+'</a></td>';$('results').innerHTML=$('results').innerHTML.split(plain).join(link);}$('results').innerHTML+='<p><button class="outline production-detail-link" onclick="openProductionDetails()">查看产物及中间配方的完整表格</button></p>';}};
// Start only after all helpers and report modules are available.
run();
