function productionFlowHTML(term='',route='auto'){
 const plan=detailCurrentPlan(),alias=unifiedAlias(term)||term;let used=(plan?.recipes||[]).map((r,i)=>({r,rate:r.out*plan.r[i],id:r.sourceId||r.id})).filter(x=>x.rate>1e-7&&(x.r.name===term||x.r.name===alias));
 if(route&&route!=='auto')used=used.filter(x=>x.id===route||x.r.id===route);
 let html='<h3>具体生产流程</h3>';
 if(!term)return html+'<p>点击结果中的产物，或输入名称／首字母查看流程。</p>';
 const candidates=used.length?used:PRODUCTS.filter(p=>searchMatch(p.name,term)&&(route==='auto'||p.id===route)).map(r=>({r,id:r.id,rate:null}));
 const seen=new Set();for(const {r,id,rate} of candidates){if(seen.has(id))continue;seen.add(id);const steps=craftFlowSteps(id);if(!steps.length)continue;
 html+='<article class="process-card"><h4>'+escapeXML(r.name)+' · '+escapeXML(r.sourceCraft||r.route)+'</h4><p class="current-craft">'+(rate===null?'参考工艺（未标为本次采用）':'本次采用 · '+fmt(rate,6)+'/min · '+fmt(rate/r.out,6)+'等价满速')+'</p><p>'+escapeXML(r.route)+'</p><ol>'+steps.map(s=>'<li>'+escapeXML(s)+'</li>').join('')+'</ol>';
 if(['S','L'].includes(r.up)||/分离芯/.test(steps.join('')))html+='<p>配料支路：息壤＋赤铜粉末→分离芯；息壤气供给方式以本次“息壤转气”设置及资源账为准。</p>';
 html+='<p>上述为依据工艺备注整理的流程概要；并行支路分别列出，不将其误作一条串联链。激活、环境和用量见下方配平表。</p></article>';}
 // Non-sale products: traverse only recipes actually used by this plan.
 const network=(plan?.recipes||[]).filter((r,i)=>r.sourceRecipe&&plan.r[i]>1e-7),ordered=[],visiting=new Set(),done=new Set();function visit(item){for(const r of network.filter(r=>r.sourceRecipe.outputs.some(o=>o.item===item))){if(done.has(r.id)||visiting.has(r.id))continue;visiting.add(r.id);for(const x of r.sourceRecipe.inputs)visit(x.item);visiting.delete(r.id);done.add(r.id);ordered.push(r);}}
 if(!candidates.some(x=>craftFlowSteps(x.id).length)){visit(term);if(ordered.length){html+='<article class="process-card"><h4>本次采用的上游加工步骤</h4><ol>'+ordered.map(r=>'<li>'+escapeXML(r.sourceRecipe.machine)+'：'+escapeXML(r.sourceRecipe.inputs.map(x=>x.item).join('＋'))+' → '+escapeXML(r.sourceRecipe.outputs.map(x=>x.item).join('＋'))+'</li>').join('')+'</ol><p>回收循环按依赖展开一次，实际共享成本以资源账为准。</p></article>';}else{const refs=RECIPE_PACKAGE.recipes.filter(r=>r.outputs.some(o=>o.item===term)&&(route==='auto'||r.id===route));html+='<p>当前没有该物品的实际生产方案；下列为参考单步配方。</p>'+detailTable(['设备','投入','产出'],refs.map(r=>[r.machine,r.inputs.map(x=>x.item).join('＋'),r.outputs.map(x=>x.item).join('＋')]));}}
 return html;
}

/* Chinese craft labels, explicit power accounting, and complete recipe reference. */
function craftName(name,id,plan){if(id==='auto')return '自动选择';if(id==='withdraw')return '自用留存';const r=PRODUCTS.find(r=>r.id===id||r.sourceId===id)||(plan?.recipes||[]).find(r=>r.id===id||r.sourceId===id);if(r)return r.route;const q=RECIPE_PACKAGE.recipes.find(r=>r.id===id);return q?q.machine:'工艺资料待核对';}
function powerCaption(c){return c.power>0||c.lowPower>0?'（已扣勾选供电自用）':'（未扣供电）';}
function powerNotice(c){return '<p class="power-notice">'+(c.power>0||c.lowPower>0?'本次仅扣除勾选的供电自用：中电 '+fmt(c.power||0)+'/min，低电 '+fmt(c.lowPower||0)+'/min；未勾选的电池不扣除。':'未勾选电池消耗：本次售卖价值未扣除供电电池，请确认实际供电需求。')+'</p>';}
function detailTable(head,rows){return rowsTable(head,rows.map(row=>row.map(x=>escapeXML(String(x??'')))));}
function recipeRateText(items,factor){return items.map(x=>x.item+' '+fmt(x.amount*factor,6)+'/min').join('；')||'无';}
function detailCurrentPlan(){const result=last?.result;return result?.free||result?.first||result;}
function productionDetailsHTML(term='',route='auto'){
const plan=detailCurrentPlan(), c=last?.cfg, text=term.trim();let html='<p>输入关键字查看产物及全部上游配方。单机表按满速每分钟配平；当前方案表按实际产率配平。激活、占用和共享设备成本以计算结果资源账为准，不能重复相加。</p>';
html+=productionFlowHTML(text,route);
if(plan?.recipes){const rows=[];plan.recipes.forEach((r,i)=>{const n=plan.r[i];if(!(n>1e-7)||text&&!searchMatch(r.name,text))return;const raw=productRaw(r,n,plan.ns?.[i]||0,plan);const ins=r.sourceRecipe?recipeRateText(r.sourceRecipe.inputs,60/r.sourceRecipe.seconds*n):['原矿','蓝铁矿','赤铜矿','息壤'].map((name,j)=>raw[j]>1e-8?name+' '+fmt(raw[j],6)+'/min':'').filter(Boolean).join('；');const outs=r.sourceRecipe?recipeRateText(r.sourceRecipe.outputs,60/r.sourceRecipe.seconds*n):r.name+' '+fmt(r.out*n,6)+'/min';rows.push([r.name,r.route,ins||'无',outs,r.sourceRecipe?'实际中间加工步骤':'整线配平（不含另列的转气、激活与占用）']);});html+='<h3>当前计算方案 · 实际配平</h3>'+detailTable(['产物／中间加工','工艺','原料输入','产物输出','范围'],rows);if(c)html+=powerNotice(c);html+='<p>整线配方没有单机路线数据时，不推测中间步骤。下方完整配方是可用资料，未必全部用于当前方案。完整资源及转气、激活成本仍见主报告。</p>';}
html+='<h3>整线工艺配料表 · 每条满速</h3>'+detailTable(['产物','工艺','原矿','蓝铁矿','赤铜矿','息壤总','息壤气总','占用','激活气','激活液化息壤','单价','产量/min'],RECIPE_PACKAGE.planningCoefficients.filter(r=>!text||searchMatch(String(r[0]),text)).map(r=>r.slice(0,12)));
const recipes=RECIPE_PACKAGE.recipes;let selected=recipes;
if(text){const names=new Set([text]),ids=new Set();let frontier=[text];for(let k=0;k<30&&frontier.length;k++){const next=[];for(const r of recipes){if(r.outputs.some(o=>frontier.some(n=>searchMatch(o.item,n)))){ids.add(r.id);for(const x of r.inputs){if(!names.has(x.item)){names.add(x.item);next.push(x.item);}}}}frontier=next;}selected=recipes.filter(r=>ids.has(r.id));}
html+='<h3>完整配方资料 · 单机满速与上游全部候选</h3>'+detailTable(['产物','设备／配方','周期/s','原料/min','输出/min','激活／环境'],selected.map(r=>[r.outputs.map(o=>o.item).join('、'),r.machine, r.seconds,recipeRateText(r.inputs,60/r.seconds),recipeRateText(r.outputs,60/r.seconds),[r.catalyst?JSON.stringify(r.catalyst):'',r.catalystPerMinute?'激活供给 '+JSON.stringify(r.catalystPerMinute)+'/min':'',r.environment||''].filter(Boolean).join('；')]));
html+='<details><summary>上传 JSON 示例的完整节点配平（不是当前计算结果）</summary><div id="flowReferenceBody">展开后读取示例配方。</div></details>';return html;}
async function loadFlowReference(){const target=$('flowReferenceBody');if(!target)return;try{const res=await fetch('src/flow-reference.json');if(!res.ok)throw Error('读取失败');const data=await res.json();const rows=data.nodes.filter(n=>n.recipe).map(n=>{const incoming=data.links.filter(l=>String(l.target?.id??l.target)===String(n.id));const outgoing=data.links.filter(l=>String(l.source?.id??l.source)===String(n.id));const labels=a=>a.map(l=>l.name+' '+l.text).join('；')||'无';return [n.name,labels(incoming),labels(outgoing),JSON.stringify(n.recipe.in),JSON.stringify(n.recipe.out)];});target.innerHTML=detailTable(['示例节点','输入实际流量','输出实际流量','原始输入配方','原始输出配方'],rows);}catch(e){target.textContent='示例暂时无法读取；完整配方资料仍可查阅。请通过网页服务器打开文件。';}}
function openProductionDetails(name='',route='auto'){const body=$('productionDetailsBody');body.innerHTML='<label>搜索产物或中间物品 <input id="productionDetailSearch" type="search" placeholder="例如：分离芯、重息壤、zt"></label><div id="productionDetailTables"></div>';$('productionDetailSearch').value=name;const refresh=()=>{$('productionDetailTables').innerHTML=productionDetailsHTML($('productionDetailSearch').value,route);loadFlowReference();};$('productionDetailSearch').oninput=()=>{route='auto';refresh();};refresh();$('productionDetailsDialog').showModal();}
$('productionDetailsOpen').onclick=()=>openProductionDetails();$('productionDetailsClose').onclick=()=>$('productionDetailsDialog').close();
const detailBaseRender=render;render=function(){detailBaseRender();if(last?.result&&!last.error){const p=detailCurrentPlan(),names=new Set([...(p?.recipes||[]).map(r=>r.name),...(p?.outputs||[]).map(r=>r.name)]);for(const row of $('results').querySelectorAll('tr')){const cells=[...row.cells];for(let i=0;i<cells.length;i++){const cell=cells[i],name=cell.textContent.trim();if(!names.has(name))continue;const nearby=cells[i+1]?.textContent.trim(),match=(p?.recipes||[]).find(r=>r.name===name&&r.route===nearby),link=document.createElement('a');link.href='#production-details';link.className='production-detail-link';link.textContent=name;link.onclick=e=>{e.preventDefault();openProductionDetails(name,match?.sourceId||match?.id||'auto');};cell.replaceChildren(link);}}$('results').insertAdjacentHTML('beforeend','<p><button class="outline production-detail-link" onclick="openProductionDetails()">查看产物生产流程与完整配平</button></p>');}};
// Start only after all helpers and report modules are available.
run();
