// Report generation and XLSX packaging run entirely in the visitor's browser.
const reportMode={integer:'整数解',engineering:'工程候选解',continuous:'连续流量＋固定占用'};
const groupName={upS:'赤铜固气上游',upL:'赤铜液气上游',furnace:'古法重息壤占用炉',envScorch:'灼铜共用酸性环境占用模块',heavy:'重息壤转固',heS:'赫铜固气末端',heL:'赫铜液气末端',scorchS:'灼铜固气末端',scorchL:'灼铜液气1末端',dragonS:'龙泡泡固气末端',dragonL:'龙泡泡液气末端'};
const cleanNumber=v=>Math.abs(v)<1e-7?0:+v.toFixed(8);
function baseReportSheets(snapshot){
 if(snapshot.cfg.free)return freeExportSheets(snapshot);
 const c=snapshot.cfg,R=snapshot.result,now=new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'});
 const sheets=[{name:'输入与口径',rows:[['终末地产线规划器 · 基建配料表第十版'],['计算输入快照','导出时刻（北京时间）',now],['参数','数值','单位或说明'],...['ore','blue','copper','solid','gas'].map((k,i)=>[['原矿','蓝铁','赤铜','息壤','天然息壤气'][i],c[k],'/min']),['外运粉末',c.powder,'/h，2原矿等价/粉末'],['外运蓝铁',c.blueTransport,'/h'],['供电自用中电',c.power,'/min，从售卖量扣除'],['供电自用低电',c.lowPower||0,'/min，从售卖量扣除'],['期望兑换价值',c.threshold,'/h'],['息壤转气',c.conversion==='S'?'固气（普通）':'液气（复杂）'],['允许商品液气',c.liquid?'是':'否'],['解的模式',reportMode[c.mode]],['外部废液/min',wasteRate(c),'全局分配'],['每4满速占用成本',c.acidCost,'息壤/min'],['活动商品',c.activity?'允许':'排除'],['可售商品',c.products.join('、')],['注意','导出的是最近一次计算输入；未计算的编辑不包含在内。'],['赫铜瓶','未给定售价，不计调度券价值；不混产。'],['工程候选','有限搜索，并非已经证明的全局最优。'],['回堵控速','普通料可按更高整口容量供给，实际消耗仍按配方。激活入口不能这样折算。'],['固定占用','所有模式都按整座/整组扣除；古法重息壤30×ceil(满速数)，灼铜固气＋液气合计1.2×ceil(总满速数/4)。'],['气体拆分','总气＝激活气＋反应气；工程激活按整数设备，不按负荷缩小。'],['期望值','达到期望额度不保证每小时能售完；这里比较的是价值。']]}, {name:'目标汇总',rows:[['目标','状态','模式','售卖价值/min','售卖价值/h','期望额度/h','差额/h','瓶产量/min','瓶等价满速','转气主输入/min','转气等价满速','启用转气机','上界（目标1价值/min；目标2瓶/min）','求解说明']]}];
 ['first','second'].forEach((key,idx)=>{if(snapshot.cfg.calcGoal&&snapshot.cfg.calcGoal!==idx+1)return;
  const p=R[key],name=idx===0?'目标一':'目标二';
  if(p)p.budgets=c.budgets;
  if(!p){sheets[1].rows.push([name,'未找到满足条件的方案',reportMode[c.mode]]);sheets.push({name:name+'说明',rows:[['状态','未找到满足条件的方案'],['提示','检查资源、供电及允许商品。工程模式未找到不代表数学上无解，可用连续模式复核。']]});return;}
  let upper=p.upper;if(idx===0&&p.mode==='engineering')upper-=powerCost(c);
  sheets[1].rows.push([name,'找到可行方案',reportMode[p.mode],p.rev,p.rev*60,c.threshold,p.rev*60-c.threshold,p.bottles,p.bottles/30,p.B,p.B/30,p.nc,Number.isFinite(upper)?upper:'',p.certificate]);
  const rows=[['目标',idx===0?'最大调度券产值':'期望兑换 · 按优先级最大化自用产物'],['解的模式',reportMode[p.mode]],['求解说明',p.certificate],[],['产物','工艺','产量/min','等价满速','售卖量/min','价值/min','外部废液分配/min','原矿等价/min','蓝铁/min','赤铜/min','普通息壤/min','固定占用息壤/min','反应气/min','控速取货方式']];
  p.recipes.forEach((recipe,i)=>{const r=p.r[i];if(r<1e-6)return;const qty=recipe.out*r,sale=recipe.expect?0:qty-powerFor(c,recipe.id),ns=p.ns?.[i]||0;rows.push([recipe.name,recipe.route,qty,r,sale,recipe.bottle?'未计价':sale*recipe.price,ns*12,...productRaw(recipe,r,ns,p),occupiedCost(recipe,r,c,p),recipe.reaction*r,control(recipe,r,ns,p)]);});
  if(p.priority)rows.push([],['优先级','自用产物','产率/min','调整最低量/min'],...p.priority.map((t,i)=>[i+1,t.name,t.rate<1e-6?0:t.rate,t.min]));if(p.mode!=='integer')rows.push([],['理论分流流程'],...planTheoryRows(p,c));
  rows.push([],['资源账','实际使用/min','容量/min','剩余/min']);const caps=[c.ore+2*c.powder/60,c.blue+c.blueTransport/60,c.copper,c.solid];p.raw.forEach((v,i)=>rows.push([['原矿等价','蓝铁等价','赤铜','息壤'][i],v,caps[i],caps[i]-v]));rows.push(['天然息壤气',p.externalGas,c.gas,c.gas-p.externalGas],['自产息壤气富余/min',p.gasSurplus||0],['外运致密原石粉末/min',c.powder/60],['中电致密粉末需求/min',p.recipes.reduce((s,t,i)=>s+(t.id==='mid'?120*p.r[i]:0),0)],[],['激活与占用','启用机台或连续等价','成本/min','成本物料']);
  Object.entries(p.count).filter(([,v])=>v>1e-7).forEach(([k,v])=>rows.push([groupName[k]||p.customEquipment?.[k]?.name||k,v,v*(p.customEquipment?.[k]?.cost??(k==='furnace'?30:k.startsWith('env')?c.acidCost:6)),k==='furnace'||k.startsWith('env')?'息壤占用成本':k==='upL'?'液化息壤':'息壤气']));
  rows.push(['息壤转气',p.nc,6*p.nc,c.conversion==='S'?'息壤气':'液化息壤'],[],['转气主输入/min',p.B],['等价满速（30主输入/台）',p.B/30],['主输入取货',p.mode==='continuous'?'连续流量 '+fmt(p.B):take(p.B)],['净供气/min',c.conversion==='S'?p.B-6*p.nc:p.B],['计价说明','自用低电与中电已扣除，赫铜瓶未计价。'],['资源说明','共用灼铜环境的占用只列在首条启用灼铜线上；产线伴随消耗与激活不可重复加账；实际总用量以资源账为准。']);
  sheets.push({name:name+'方案',rows});
 });sheets[0].rows.push([],['自用优先级','物品','调整最低量/min'],...(c.expectTargets||[]).map((t,i)=>[i+1,t.name,t.min]));if(c.mode==='continuous')sheets[0].rows.push([],['器具上限','分流器','汇流器','限速器','储物箱','取货口'],['上限',...Object.keys(MIX_LIMITS).map(k=>c.budgets?.[k]??MIX_LIMITS[k])]);return sheets;
}
function escapeXML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function columnLetters(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function sheetXML(rows){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="28" customWidth="1"/><col min="2" max="2" width="36" customWidth="1"/><col min="3" max="20" width="24" customWidth="1"/></cols><sheetData>'+rows.map((r,i)=>'<row r="'+(i+1)+'">'+r.map((v,j)=>{const ref=columnLetters(j)+(i+1),style=i===0?1:0;if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}" s="2"><v>${cleanNumber(v)}</v></c>`;return `<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${escapeXML(v??'')}</t></is></c>`;}).join('')+'</row>').join('')+'</sheetData></worksheet>';}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zipStore(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0,cdLength=0;const pack=(n)=>new Uint8Array(n),set=(a,i,n,len)=>{const d=new DataView(a.buffer);len===2?d.setUint16(i,n,true):d.setUint32(i,n,true)};
 for(const [name,content] of files){const f=enc.encode(name),data=enc.encode(content),crc=crc32(data),h=pack(30+f.length);set(h,0,0x04034b50,4);set(h,4,20,2);set(h,6,0x800,2);set(h,12,33,2);set(h,14,crc,4);set(h,18,data.length,4);set(h,22,data.length,4);set(h,26,f.length,2);h.set(f,30);parts.push(h,data);
 const c=pack(46+f.length);set(c,0,0x02014b50,4);set(c,4,20,2);set(c,6,20,2);set(c,8,0x800,2);set(c,14,33,2);set(c,16,crc,4);set(c,20,data.length,4);set(c,24,data.length,4);set(c,28,f.length,2);set(c,42,offset,4);c.set(f,46);central.push(c);offset+=h.length+data.length;cdLength+=c.length;}
 const end=pack(22);set(end,0,0x06054b50,4);set(end,8,files.length,2);set(end,10,files.length,2);set(end,12,cdLength,4);set(end,16,offset,4);const all=[...parts,...central,end],out=pack(offset+cdLength+22);let pos=0;for(const part of all){out.set(part,pos);pos+=part.length}return out;
}
function xlsxBytes(sheets){const ns='http://schemas.openxmlformats.org',files=[['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="${ns}/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${ns}/package/2006/relationships"><Relationship Id="rId1" Type="${ns}/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`],['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="${ns}/spreadsheetml/2006/main" xmlns:r="${ns}/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${escapeXML(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${ns}/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${ns}/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${ns}/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],['xl/styles.xml',`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${ns}/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Microsoft YaHei"/></font><font><b/><sz val="12"/><color rgb="FFFFFFFF"/><name val="Microsoft YaHei"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF162230"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"><alignment vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`]];
 sheets.forEach((s,i)=>files.push([`xl/worksheets/sheet${i+1}.xml`,sheetXML(s.rows)]));return zipStore(files);
}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function readyExport(){if(!last){$('exportStatus').textContent='请先完成一次计算。';return false}return true}
function exportXlsx(){if(!readyExport())return;try{const bytes=xlsxBytes(reportSheets(last));saveBlob(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'终末地产线规划报告.xlsx');$('exportStatus').textContent=last.cfg.free?'Excel已生成：含自由输入、资源缺口和取货方案。':'Excel已生成：含当前模式输入参数和方案。'}catch(e){$('exportStatus').textContent='导出失败：'+e.message;}}
function printReportHTML(){const saved=active;let sections=[];try{for(const i of (last.cfg.free?[2]:last.cfg.calcGoal?[last.cfg.calcGoal]:[1,2])){active=i;render();sections.push(`<section class="report-plan"><h2>${last.cfg.free?'自由模式':i===1?'目标一 · 最大调度券产值':'目标二 · 期望兑换'}</h2>${$('results').innerHTML.replace(/<details\b([^>]*)>/g,'<details$1 open>').replace(/<button\b[^>]*class="outline take-details-toggle"[^>]*>.*?<\/button>/g,'')}</section>`);}}finally{active=saved;render();}
 const input=reportSheets(last)[0].rows.slice(2).map(r=>`<tr>${r.map(v=>`<td>${escapeXML(v)}</td>`).join('')}</tr>`).join('');
 return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><title>终末地产线规划报告</title><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{color:#152331;font:14px/1.55 system-ui,'Microsoft YaHei',sans-serif;margin:24px}h1{font-size:25px}h2{font-size:21px;margin-top:24px}h3{font-size:17px}.report-plan{break-before:page}.result-head{display:flex;justify-content:space-between;gap:20px}.badge{font-size:14px}.result-head h2{font-size:24px}.result-head small{font-size:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats label{display:block;font-size:13px}.stats strong{font-size:19px}.table-scroll{overflow:visible}table{border-collapse:collapse;width:100%;font-size:12px;table-layout:auto}td,th{padding:6px;border:1px solid #bdcbd4;text-align:left;vertical-align:top;overflow-wrap:anywhere}thead{display:table-header-group}tr{break-inside:avoid}h2,h3{break-after:avoid}p{orphans:3;widows:3}.capacity-note{border-left:3px solid #366;padding:10px}.toolbar{padding:15px;background:#edf2f5}.toolbar button{font-size:16px;padding:8px 16px;cursor:pointer}.hint,.result-note{color:#425466}.rule-note{border:1px solid #bdcbd4;padding:12px}@media print{.toolbar{display:none}body{margin:0}a{color:inherit}}</style></head><body><div class="toolbar"><button onclick="window.print()">打印 / 保存为PDF</button> 在打印目标中选择“另存为PDF”，推荐A4横向。</div><h1>终末地产线规划报告</h1><p>基建配料表第十版 · 导出时间 ${escapeXML(new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}（北京时间）</p><h2>计算输入快照</h2><table>${input}</table>${sections.join('')}${last&&(last.cfg.free?last.result.free:last.result.first)?.feasible?resumePDFHTML(last):''}<div class="rule-note"><strong>复核口径：</strong>工程解优先控制可简单取出的普通原料，其他普通料足量供给、回堵控速。激活入口不能这样折算；半速固气灼铜仍需18激活＋15反应＝33气/min。当前工程候选搜索未穷尽所有接法，连续流量允许激活折算，但占用仍取整数。已勾选的供电自用低电与中电已从销售扣除；达到期望额度不保证每小时售完。</div></body></html>`;
}
function exportPdf(){if(!readyExport())return;const w=window.open('','_blank');if(!w){$('exportStatus').textContent='浏览器阻止了报告窗口，请允许弹窗后重试。';return}try{w.document.open();w.document.write(printReportHTML());w.document.close();w.document.title='终末地产线规划报告';w.focus();$('exportStatus').textContent='报告已打开，请在打印目标中选择“另存为PDF”。';setTimeout(()=>{w.print();},300);}catch(e){$('exportStatus').textContent='报告生成失败：'+e.message;}}
$('exportExcel').onclick=exportXlsx;$('exportPdf').onclick=exportPdf;
$('manualOpen').onclick=()=>$('manualDialog').showModal();$('manualClose').onclick=()=>$('manualDialog').close();$('manualDialog').onclick=e=>{if(e.target===$('manualDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
if(typeof location!=='undefined'&&location.protocol==='file:'){$('signin').hidden=true;}

function reportSheets(snapshot){const sheets=baseReportSheets(snapshot);try{sheets.push({name:"恢复数据",rows:resumeDataRows(snapshot)});}catch{}return sheets;}
