// Compatibility for browsers predating typed-array encoding helpers.
(()=>{const U=Uint8Array,P=U.prototype;if(!P.toHex)Object.defineProperty(P,'toHex',{value:function(){return Array.from(this,x=>x.toString(16).padStart(2,'0')).join('');}});if(!P.toBase64)Object.defineProperty(P,'toBase64',{value:function(){let s='';for(const x of this)s+=String.fromCharCode(x);return btoa(s);}});if(!U.fromBase64)U.fromBase64=s=>U.from(atob(s),x=>x.charCodeAt(0));if(!U.fromHex)U.fromHex=s=>{if(!/^(?:[0-9a-f]{2})*$/i.test(s))throw Error('Invalid hex');return U.from(s.match(/../g)||[],x=>parseInt(x,16));};})();
// Report files are read locally. No upload or account is needed.
const RESUME_VERSION=1;
if(!Uint8Array.prototype.toHex)Object.defineProperty(Uint8Array.prototype,'toHex',{value:function(){return Array.from(this,x=>x.toString(16).padStart(2,'0')).join('');},configurable:true});
function resumeSnapshot(snapshot=last){if(!snapshot)throw Error('请先计算');const c=snapshot.cfg,p=c.free?snapshot.result.free:snapshot.result.first;if(!p?.feasible)throw Error('只可恢复可行的生产计划');const targets=[];const add=(name,route,qty)=>{if(qty<1e-6)return;const old=targets.find(t=>t.name===name&&t.route===route);if(old)old.qty+=qty;else targets.push({name,route,qty});};if(c.free){(p.outputs||[]).forEach((t,j)=>{const rs=p.recipes.filter(r=>r.target===j&&!r.withdraw);if(rs.length){for(const r of rs){const i=p.recipes.indexOf(r);add(t.name,r.sourceId||t.route||'auto',r.out*p.r[i]);}}else add(t.name,t.route||'auto',t.rate);});}else p.recipes.forEach((r,i)=>{if(!r.network&&!r.withdraw)add(r.name,r.sourceId||r.id,r.out*p.r[i]);});return{kind:'endfield-plan',version:RESUME_VERSION,created:new Date().toISOString(),cfg:{...c,expectCatalog:undefined,expectTargets:undefined,nextTargets:undefined,fixedTargets:undefined,freeTargets:undefined},targets};}
function encodeResume(snapshot){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(snapshot))));}
function decodeResume(text){const a=text.indexOf('EFPLAN_BEGIN'),b=text.indexOf('EFPLAN_END',a);if(a<0||b<0)return null;const data=text.slice(a+12,b).replace(/\s/g,'');if(data.length>2000000)throw Error('恢复数据过大');return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(data),c=>c.charCodeAt(0))));}
function resumeDataRows(snapshot){const b=encodeResume(resumeSnapshot(snapshot));return [['EFPLAN_BEGIN'],...b.match(/.{1,160}/g).map(x=>[x]),['EFPLAN_END']];}
function resumePDFHTML(snapshot){return '<section class="report-plan"><h2>续算恢复数据</h2><p>请保留本页，以便下次导入此PDF。仅保存规划参数及最终产率。</p><div style="font:9px/1.3 monospace;white-space:pre">'+resumeDataRows(snapshot).map(r=>r[0]).join('\n')+'</div></section>';}
async function excelRows(file){const zip=await JSZip.loadAsync(await file.arrayBuffer());const parser=new DOMParser(),shared=[];if(zip.file('xl/sharedStrings.xml')){const d=parser.parseFromString(await zip.file('xl/sharedStrings.xml').async('string'),'application/xml');for(const si of d.getElementsByTagName('si'))shared.push([...si.getElementsByTagName('t')].map(t=>t.textContent).join(''));}const rows=[];for(const path of Object.keys(zip.files).filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x)).sort()){const xml=await zip.file(path).async('string');if(xml.length>20000000)throw Error('Excel内容过大');const d=parser.parseFromString(xml,'application/xml');for(const row of d.getElementsByTagName('row')){const cells=[];for(const c of row.getElementsByTagName('c')){const letters=(c.getAttribute('r')||'A').match(/^[A-Z]+/)[0];let col=0;for(const x of letters)col=col*26+x.charCodeAt(0)-64;const type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0]?.textContent||'';cells[col-1]=type==='s'?shared[+v]:type==='inlineStr'?[...c.getElementsByTagName('t')].map(t=>t.textContent).join(''):v;}rows.push(cells);}}return rows;}
function legacyExcelSnapshot(rows){const number=v=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)&&n>=0?n:null;},c={...cfg(),free:true,unifiedFree:true},targets=[];const found=new Set;const labels={ore:'原矿',blue:'蓝铁',copper:'赤铜',solid:'息壤',gas:'天然息壤气',powder:'外运粉末',blueTransport:'外运蓝铁',power:'供电自用中电',lowPower:'供电自用低电',threshold:'期望兑换价值'};for(const r of rows){for(const[k,name]of Object.entries(labels))if(r[0]===name&&number(r[1])!==null){c[k]=number(r[1]);found.add(k);}if(['ore','blue','copper','solid','gas','powder','blueTransport','waste','acidCost'].includes(r[0])&&number(r[1])!==null){c[r[0]]=number(r[1]);found.add(r[0]);}if(['解模式','解的模式'].includes(r[0]))c.mode=String(r[1]).includes('整数')?'integer':String(r[1]).includes('工程')?'engineering':'continuous';if(r[0]==='期望价值/h')c.threshold=number(r[1]);if(r[0]==='conversion')c.conversion=r[1];if(r[0]==='liquid')c.liquid=['1','true','是'].includes(String(r[1]));if(r[0]==='外部废液/min')c.waste=number(r[1]);if(r[0]==='活动商品')c.activity=r[1]==='允许';if(r[0]==='供电中电/min')c.power=number(r[1]);if(r[0]==='供电低电/min')c.lowPower=number(r[1]);if(r[0]==='息壤转气')c.conversion=String(r[1]).includes('液')?'L':'S';if(r[0]==='允许商品液气')c.liquid=r[1]==='是';}
if(['ore','blue','copper','solid','gas'].some(k=>!found.has(k)))throw Error('旧Excel缺少完整基础资源参数，无法可靠恢复');c.node=(c.waste||0)>0;let nativeHeader=false,totalHeader=false;for(const r of rows){if(r[0]==='计划类别'&&r[1]==='物品'){totalHeader=true;nativeHeader=false;continue;}if(r[0]==='产物'&&r[1]==='工艺'&&String(r[2]).includes('产量')){nativeHeader=true;totalHeader=false;continue;}if(!r.length||r[0]==='基础资源'||r[0]==='资源账'||r[0]==='理论分流流程'){nativeHeader=false;totalHeader=false;}if(totalHeader&&['原固定计划','新增优先级','供电自动补足'].includes(r[0])&&planItems.includes(r[1])&&number(r[3])!==null)targets.push({name:r[1],route:r[2]==='自动'?'auto':r[2],qty:number(r[3])});else if(nativeHeader&&planItems.includes(r[0])&&number(r[2])!==null){const p=PRODUCTS.find(p=>p.name===unifiedAlias(r[0])&&(p.route===r[1]||p.id==='scorchL'&&r[1]==='液气'));if(p)targets.push({name:r[0],route:p.id,qty:number(r[2])});}}if(!targets.length)throw Error('旧Excel缺少最终产率表，无法可靠恢复。请使用新版导出的报告。');return{kind:'endfield-plan',version:1,cfg:c,targets};}
async function readResumeFile(file){if(!file)throw Error('请选择Excel或PDF');if(file.size>25*1024*1024)throw Error('报告不能超过25MB');if(/\.xlsx$/i.test(file.name)){const rows=await excelRows(file);return decodeResume(rows.flat().join('\n'))||legacyExcelSnapshot(rows);}if(/\.pdf$/i.test(file.name)){const pdfjs=await import('./vendor/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('vendor/pdf.worker.min.mjs',document.currentScript?.src||new URL('src/resume.js',location.href)).href;const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;try{if(pdf.numPages>150)throw Error('PDF页数过多');let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);text+=(await page.getTextContent()).items.map(x=>x.str).join('\n')+'\n';}const data=decodeResume(text);if(!data)throw Error('这个PDF没有可恢复数据（可能是旧版报告或截图PDF）。请导入对应Excel，或用新版重新导出PDF。');return data;}finally{await pdf.destroy();}}throw Error('只支持.xlsx和.pdf报告');}
function validateResume(data){if(data?.kind!=='endfield-plan'||data.version!==1||!Array.isArray(data.targets)||data.targets.length>200)throw Error('报告格式不兼容');const c=data.cfg;if(!c||!['S','L'].includes(c.conversion)||!['continuous','integer','engineering'].includes(c.mode))throw Error('工艺参数无效');if(c.region==='valley')throw Error('四号谷地计算暂未开放');for(const k of ['ore','blue','copper','solid','gas','powder','blueTransport','power','lowPower','threshold','acidCost','waste'])if(c[k]!==undefined&&(!Number.isFinite(c[k])||c[k]<0||c[k]>1000000))throw Error('报告资源参数无效：'+k);for(const t of data.targets){if(!planItems.includes(t.name)||!Number.isFinite(t.qty)||t.qty<0||t.qty>10000)throw Error('报告物品或产率无效');const alias=unifiedAlias(t.name);if(t.route!=='auto'&&!PRODUCTS.some(p=>p.name===alias&&p.id===t.route)&&!RECIPE_PACKAGE.recipes.some(r=>r.id===t.route))throw Error('未知工艺：'+t.route);}return data;}
function applyResume(data){validateResume(data);if(worker)worker.terminate();const c=data.cfg;$('region').value='wuling';regionSwitch();$('current').checked=false;$('engineerPreset').checked=false;$('extremePreset').checked=false;for(const k of ['ore','blue','copper','solid','gas','threshold','waste','acidCost','power','lowPower'])if(Number.isFinite(c[k]))$(k).value=c[k];$('mode').value=c.mode;$('conversion').value=c.conversion;$('liquid').value=c.liquid?'yes':'no';$('activity').checked=!!c.activity;$('useMidPower').checked=(c.power||0)>0;$('useLowPower').checked=(c.lowPower||0)>0;$('node').checked=!!c.node;$('transport').value=c.powder?'powder':c.blueTransport?'blue':'none';$('transportAmount').value=c.powder||c.blueTransport||0;for(const[k,v]of Object.entries(c.budgets||{})){if($('budget_'+k)){$('budget_'+k).value=v;clampBudgetInput($('budget_'+k),true);}}for(const kind of ['fixed','next']){for(const i of planRows[kind])$(kind+'Row'+i).remove();planRows[kind].length=0;}for(const t of data.targets){addPlanRow('fixed');const i=planRows.fixed.at(-1);$('fixedItem'+i).value=t.name;refreshCrafts('fixed',i);const select=$('fixedRoute'+i);if(t.route!=='auto'&&!planCrafts(t.name).some(o=>o.id===t.route))throw Error(t.name+'工艺被报告中的权限禁止');select.value=t.route||'auto';$('fixedQty'+i).value=t.qty;}while(planRows.fixed.length<2)addPlanRow('fixed');for(let i=0;i<2;i++)addPlanRow('next');active=2;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('selected',t.dataset.tab==='2'));state();clearUnifiedResult();unifiedState();resumePending=true;unifiedPhase=1;run();}
let resumePending=false;const originalRenderFree=renderFree;renderFree=function(){originalRenderFree();if(resumePending&&last?.result?.free){resumePending=false;if(last.result.free.feasible){unifiedPhase=2;$('resumeStatus').textContent='已恢复上次最终产率并核算剩余资源。请在第二步添加新产物；共享设备以重新计算结果为准。';$('nextPanel').scrollIntoView?.({behavior:'smooth',block:'start'});}else $('resumeStatus').textContent='已恢复参数，但该计划在当前配方中不可实现，请查看资源缺口。';}};
$('resumeImport').onclick=async()=>{try{$('resumeImport').disabled=true;$('resumeStatus').textContent='正在读取报告…';const data=await readResumeFile($('resumeFile').files[0]);applyResume(data);}catch(e){$('resumeStatus').textContent='导入失败：'+e.message;}finally{$('resumeImport').disabled=false;}};
function syncFloating(){const top=window.scrollY||document.documentElement.scrollTop||0;$('backToTop').hidden=top<=0;$('floatingCalculate').disabled=$('region').value==='valley'||$('calculateTop').disabled;$('floatingCalculate').textContent=active===1?'计算模式1':baselineReady?'计算第二步':'核算第一步';}
window.addEventListener('scroll',syncFloating,{passive:true});$('floatingCalculate').onclick=()=>{if(active===2){unifiedPhase=baselineReady?2:1;}run();syncFloating();};const oldUnifiedState=unifiedState;unifiedState=function(){oldUnifiedState();syncFloating();};setInterval(syncFloating,300);syncFloating();

$('download').textContent='下载网站ZIP';$('download').onclick=async()=>{try{$('download').disabled=true;const zip=new JSZip(),root=document.documentElement.cloneNode(true);for(const id of ['fixedRows','nextRows','baselineResult','results'])root.querySelector('#'+id).innerHTML='';root.querySelector('#unifiedPanel').hidden=true;root.querySelector('#nextPanel').hidden=true;root.querySelectorAll('.tab').forEach(t=>t.classList.toggle('selected',t.dataset.tab==='1'));zip.file('index.html','<!doctype html>\n'+root.outerHTML);const paths=[...new Set([...root.querySelectorAll('script[src],link[rel=stylesheet]')].map(x=>x.getAttribute('src')||x.getAttribute('href')).concat(['src/solver-worker.js','src/vendor/pdf.min.mjs','src/vendor/pdf.worker.min.mjs']))];for(const path of paths){const response=await fetch(path);if(!response.ok)throw Error('读取网站文件失败');zip.file(path,await response.arrayBuffer());}saveBlob(await zip.generateAsync({type:'blob'}),'终末地产线规划器.zip');}catch(e){$('exportStatus').textContent='下载失败：'+e.message+'。可从GitHub仓库下载完整ZIP。';}finally{$('download').disabled=false;}};

// All split scripts are loaded before the initial Worker calculation.
run();
