// Two-phase primal simplex, with bounded branch-and-bound for activated equipment.
function lp(A,b,c){const m=b.length,n=c.length,B=Array.from({length:m},(_,i)=>n+i),N=Array.from({length:n+1},(_,i)=>i);N[n]=-1;const D=Array.from({length:m+2},()=>Array(n+2).fill(0));for(let i=0;i<m;i++){for(let j=0;j<n;j++)D[i][j]=A[i][j];D[i][n]=-1;D[i][n+1]=b[i]}for(let j=0;j<n;j++)D[m][j]=-c[j];D[m+1][n]=1;
 function pivot(r,s){let v=1/D[r][s];for(let i=0;i<m+2;i++)if(i!==r)for(let j=0;j<n+2;j++)if(j!==s)D[i][j]-=D[r][j]*D[i][s]*v;for(let j=0;j<n+2;j++)if(j!==s)D[r][j]*=v;for(let i=0;i<m+2;i++)if(i!==r)D[i][s]*=-v;D[r][s]=v;[B[r],N[s]]=[N[s],B[r]]}
 function simplex(phase){let x=phase===1?m+1:m;for(let iter=0;iter<20000;iter++){let s=-1;for(let j=0;j<=n;j++){if(phase===2&&N[j]===-1)continue;if(s<0||D[x][j]<D[x][s]-1e-9||(Math.abs(D[x][j]-D[x][s])<1e-9&&N[j]<N[s]))s=j}if(D[x][s]>=-1e-8)return true;let r=-1;for(let i=0;i<m;i++){if(D[i][s]<=1e-9)continue;if(r<0||D[i][n+1]/D[i][s]<D[r][n+1]/D[r][s]-1e-9)r=i}if(r<0)return false;pivot(r,s)}throw Error('求解迭代超限，请缩小资源范围')}
 let r=0;for(let i=1;i<m;i++)if(D[i][n+1]<D[r][n+1])r=i;if(m&&D[r][n+1]<-1e-8){pivot(r,n);if(!simplex(1)||D[m+1][n+1]<-1e-7)return null;for(let i=0;i<m;i++)if(B[i]===-1){let s=0;for(let j=1;j<=n;j++)if(D[i][j]<D[i][s])s=j;if(Math.abs(D[i][s])>1e-8)pivot(i,s)}}if(!simplex(2))throw Error('模型无界：请填写有限资源');const x=Array(n).fill(0);for(let i=0;i<m;i++)if(B[i]>=0&&B[i]<n)x[B[i]]=Math.max(0,D[i][n+1]);return{x,value:D[m][n+1]}}
const PRODUCTS=[
{id:'low',name:'低电',route:'普通',out:6,price:25,raw:[180,0,0,30],reaction:0},
{id:'blue',name:'蓝药',route:'普通',out:6,price:16,raw:[0,120,0,0],reaction:0},
{id:'purple',name:'紫药',route:'普通',out:6,price:22,raw:[0,0,120,0],reaction:0},
{id:'mid',name:'中电',route:'主反应＋提纯',out:6,price:54,raw:[240,30,0,48],reaction:0,node:true},
{id:'heA',name:'赫铜',route:'古法',out:6,price:48,raw:[0,30,240,0],reaction:0},
{id:'heS',name:'赫铜',route:'固气',out:6,price:48,raw:[0,0,150,15],reaction:0,up:'S',end:'heS',endCap:1},
{id:'heL',name:'赫铜',route:'液气',out:6,price:48,raw:[0,0,150,15],reaction:0,up:'L',end:'heL',endCap:1},
{id:'heavyA',name:'重息壤',route:'古法',out:6,price:27,raw:[0,0,0,84],reaction:0,furnace:true,occupancy:30,node:true},
{id:'heavyS',name:'重息壤',route:'固气',out:12,price:27,raw:[0,0,30,15],reaction:60,end:'heavy',endCap:1},
{id:'scorchS',name:'灼铜',route:'固气',out:6,price:70,raw:[0,0,150,15],reaction:30,up:'S',end:'scorchS',endCap:1,environment:'envScorch',occupancy:1.2,occupancyCapacity:4},
{id:'scorchL',name:'灼铜',route:'液气1',out:6,price:70,raw:[0,0,150,15],reaction:30,up:'L',end:'scorchL',endCap:1,environment:'envScorch',occupancy:1.2,occupancyCapacity:4},
{id:'scorch2L',name:'灼铜',route:'液气2',out:6,price:70,raw:[0,0,240,0],reaction:30,customActivation:{key:'scorchLiquid2Activation',resource:3,cost:6,name:'灼铜液气2 · 液化息壤激活'},environment:'envScorch',occupancy:1.2,occupancyCapacity:4},
{id:'bubble',name:'息壤龙泡泡',route:'古法（活动）',out:6,price:100,raw:[0,0,120,60],reaction:0,activity:true},
{id:'dragonS',name:'重息壤龙泡泡',route:'固气（活动）',out:6,price:200,raw:[0,0,150,15],reaction:90,up:'S',end:'dragonS',endCap:2,activity:true},
{id:'dragonL',name:'重息壤龙泡泡',route:'液气（活动）',out:6,price:200,raw:[0,0,150,15],reaction:90,up:'L',end:'dragonL',endCap:2,activity:true},
{id:'bottleA',name:'赫铜瓶',route:'古法',out:30,price:0,raw:[0,60,480,0],reaction:0,bottle:true},
{id:'bottleS',name:'赫铜瓶',route:'固气',out:30,price:0,raw:[0,0,300,30],reaction:0,up:'S',end:'heS',endCap:2,bottle:true},
{id:'bottleL',name:'赫铜瓶',route:'液气',out:30,price:0,raw:[0,0,300,30],reaction:0,up:'L',end:'heL',endCap:2,bottle:true}];
const V10_COEFFICIENTS={"low":{"solidTotal":30,"activationGas":0,"activationLiquid":0,"gasTotal":0},"blue":{"solidTotal":0,"activationGas":0,"activationLiquid":0,"gasTotal":0},"purple":{"solidTotal":0,"activationGas":0,"activationLiquid":0,"gasTotal":0},"mid":{"solidTotal":48,"activationGas":0,"activationLiquid":0,"gasTotal":0},"heA":{"solidTotal":0,"activationGas":0,"activationLiquid":0,"gasTotal":0},"heS":{"solidTotal":15,"activationGas":18,"activationLiquid":0,"gasTotal":18},"heL":{"solidTotal":27,"activationGas":6,"activationLiquid":0,"gasTotal":6},"heavyA":{"solidTotal":84,"activationGas":0,"activationLiquid":0,"gasTotal":0},"heavyS":{"solidTotal":15,"activationGas":6,"activationLiquid":0,"gasTotal":66},"scorchS":{"solidTotal":15,"activationGas":18,"activationLiquid":0,"gasTotal":48},"scorchL":{"solidTotal":27,"activationGas":6,"activationLiquid":12,"gasTotal":36},"bubble":{"solidTotal":60,"activationGas":0,"activationLiquid":0,"gasTotal":0},"dragonS":{"solidTotal":15,"activationGas":24,"activationLiquid":0,"gasTotal":114},"dragonL":{"solidTotal":27,"activationGas":12,"activationLiquid":12,"gasTotal":102},"bottleA":{"solidTotal":0,"activationGas":0,"activationLiquid":0,"gasTotal":0},"bottleS":{"solidTotal":30,"activationGas":36,"activationLiquid":0,"gasTotal":36},"bottleL":{"solidTotal":54,"activationGas":12,"activationLiquid":0,"gasTotal":12},"scorch2L":{"solidTotal":6,"activationGas":0,"activationLiquid":6,"gasTotal":30}};
PRODUCTS.forEach(p=>{const c=V10_COEFFICIENTS[p.id];Object.assign(p,c);p.raw[3]=c.solidTotal-c.activationLiquid;p.reaction=c.gasTotal-c.activationGas;if(p.up==='L'&&c.activationLiquid===0)delete p.up});
const T=[0,5,6,10,12,15,18,20,24,25,30];
function standard(v){let k=Math.floor((v+1e-7)/30),t=v-30*k;return T.some(x=>Math.abs(x-t)<1e-6)}
function wasteRate(c){return c.node?(c.waste===undefined?12:c.waste):0}
function powerFor(c,id){return id==='mid'?(c.power||0):id==='low'?(c.lowPower||0):0}
function powerCost(c){return (c.power||0)*54+(c.lowPower||0)*25}
function build(cfg,goal,bottleRoute){const recipes=PRODUCTS.concat(cfg.expectExtras||[]).filter(p=>{if(p.expect)return !p.bottle||p.sourceId===bottleRoute;if(!cfg.free&&cfg.expectTargets&&p.bottle)return false;if(cfg.free){const t=cfg.freeTargets.find(t=>t.name===p.name);return t&&(t.qty>0||t.maximize||powerFor(cfg,p.id)>0)&&(!p.activity||cfg.activity)&&(!p.id.endsWith('L')||cfg.liquid)&&(t.route==='auto'||t.route===p.id)&&(!p.bottle||!cfg.freeBottleRoute||p.id===cfg.freeBottleRoute)}return(p.bottle||cfg.products.includes(p.name))&&(!p.activity||cfg.activity)&&(!p.id.endsWith('L')||cfg.liquid)&&(!p.bottle||goal===2&&p.id===bottleRoute)});if(!cfg.free)for(const id of ['mid','low'])if(powerFor(cfg,id)>0&&!recipes.some(p=>p.id===id))throw Error('供电自用量大于0时必须允许生产'+(id==='mid'?'中电':'低电'));const n=recipes.length;let vars=recipes.map(p=>p.id),costs=recipes.map(p=>p.out*p.price),obj=costs.slice();if(goal===2)obj=recipes.map(p=>p.bottle?p.out:0);const A=[],b=[],ints=[];function variable(name){vars.push(name);obj.push(0);costs.push(0);for(const r of A)r.push(0);return vars.length-1}function row(entries,rhs){const a=Array(vars.length).fill(0);for(const [i,v]of entries)a[i]=v;A.push(a);b.push(rhs)}const resource=Array.from({length:5},()=>Array(vars.length).fill(0));recipes.forEach((p,i)=>{for(let j=0;j<4;j++)resource[j][i]=p.raw[j];resource[4][i]=p.reaction;if(powerFor(cfg,p.id)>0)row([[i,-p.out]],-powerFor(cfg,p.id));if(cfg.mode==='integer'&&!p.withdraw)ints.push(i)});
 let groups={};function group(name,i,cap){if(!groups[name])groups[name]=[];groups[name].push([i,cap])}recipes.forEach((p,i)=>{if(p.up)group('up'+p.up,i,p.bottle?4:2);if(p.end)group(p.end,i,p.endCap);if(p.furnace)group('furnace',i,1);if(p.environment)group(p.environment,i,1/p.occupancyCapacity);if(p.customActivation)group(p.customActivation.key,i,1)});
 let equipment={};for(const [name,members]of Object.entries(groups)){let j=variable(name);equipment[name]=j;row([...members,[j,-1]],0);if(cfg.mode!=='continuous'||name==='furnace'||name.startsWith('env'))ints.push(j);for(const r of resource)r.push(0);const meta=recipes.find(p=>p.customActivation?.key===name)?.customActivation;resource[meta?meta.resource:name==='upL'||name==='furnace'||name.startsWith('env')?3:4][j]=meta?meta.cost:name==='furnace'?30:name.startsWith('env')?cfg.acidCost:6;if(cfg.mode!=='continuous'&&(name.startsWith('up')||name.startsWith('dragon'))){let k=variable('chains_'+name);for(const r of resource)r.push(0);row([[j,1],[k,-2]],0);row([[j,-1],[k,2]],0);ints.push(k)}}
 let nodes=[];if(cfg.node)recipes.forEach((p,i)=>{if(p.node){let j=variable('node_'+p.id);nodes.push([j,1]);for(const r of resource)r.push(0);resource[3][j]=-9.6;row([[j,.2],[i,-1]],0)}});if(nodes.length)row(nodes,wasteRate(cfg)/12);
 let acidIndex=-1;
 let conv=variable('conversion');for(const r of resource)r.push(0);let convN=-1;if(cfg.mode==='continuous'){resource[3][conv]=cfg.conversion==='S'?30:36;resource[4][conv]=cfg.conversion==='S'?-24:-30}else{resource[3][conv]=30;resource[4][conv]=-30;convN=variable('converter');for(const r of resource)r.push(0);resource[cfg.conversion==='S'?4:3][convN]=6;row([[conv,1],[convN,-1]],0);ints.push(convN);if(cfg.mode==='integer')ints.push(conv)}
 const caps=[cfg.ore+2*cfg.powder/60,cfg.blue+cfg.blueTransport/60,cfg.copper,cfg.solid,cfg.gas];resource.forEach((r,i)=>{while(r.length<vars.length)r.push(0);A.push(r);b.push(caps[i])});if(cfg.free){const target=cfg.freeTargets.find(t=>t.maximize);obj=vars.map((k,i)=>target&&recipes[i]?.name===target.name?recipes[i].out:0);for(const t of cfg.freeTargets){const entries=recipes.map((p,i)=>[i,p.name===t.name?p.out:0]);const q=Math.max(t.qty,powerFor(cfg,t.name==='中电'?'mid':t.name==='低电'?'low':''));row(entries.map(([i,v])=>[i,-v]),-q);if(!t.maximize)row(entries,q)}}if(goal===2)row(costs.map((v,i)=>[i,-v]),-(cfg.threshold/60+powerCost(cfg)));return{recipes,n,vars,A,b,obj,costs,ints,resource,caps,equipment,conv,convN,acidIndex,goal,cfg}}
function validSolution(m,s){if(!s||s.x.length!==m.vars.length)return null;if(m.ints.some(i=>Math.abs(s.x[i]-Math.round(s.x[i]))>1e-5)||s.x.some(v=>v< -1e-7)||m.A.some((a,j)=>a.reduce((v,t,i)=>v+t*s.x[i],0)>m.b[j]+1e-5))return null;return{x:s.x.slice(),value:m.obj.reduce((v,t,i)=>v+t*s.x[i],0)}}
function seedSolution(m,p){if(!p)return null;const values={conversion:p.B/30,converter:p.nc};p.recipes.forEach((r,i)=>{values[r.id]=p.r[i];values['node_'+r.id]=p.ns?.[i]||0});for(const [k,v]of Object.entries(p.count)){values[k]=v;values['chains_'+k]=v/2}return validSolution(m,{x:m.vars.map(k=>values[k]||0)})}
function mip(model,limit=2500,initial=null){let best=validSolution(model,initial),root=lp(model.A,model.b,model.obj);if(!root)return null;let queue=[{A:model.A,b:model.b,s:root}],nodes=0,t0=Date.now(),upper=root.value;while(queue.length&&nodes++<limit&&Date.now()-t0<8000){queue.sort((a,b)=>a.s.value-b.s.value);let q=queue.pop();if(best&&q.s.value<=best.value+1e-7)continue;let j=-1,f=0;for(const i of model.ints){const d=Math.abs(q.s.x[i]-Math.round(q.s.x[i]));if(d>f+1e-7){f=d;j=i}}if(j<0){best=q.s;continue}const v=q.s.x[j];for(const [sign,bound]of [[1,Math.floor(v)],[-1,-Math.ceil(v)]]){const a=Array(model.vars.length).fill(0);a[j]=sign;const aa=q.A.concat([a]),bb=q.b.concat([bound]),s=lp(aa,bb,model.obj);if(s&&(!best||s.value>best.value+1e-7))queue.push({A:aa,b:bb,s})}}if(!best){let A=model.A.slice(),b=model.b.slice();for(const i of model.ints){const a=Array(model.vars.length).fill(0);a[i]=1;A.push(a);b.push(Math.ceil(root.x[i]-1e-8));const d=a.map(v=>-v);A.push(d);b.push(-Math.ceil(root.x[i]-1e-8))}best=lp(A,b,model.obj)}best=validSolution(model,best);return best?{...best,exact:queue.length===0,upper:queue.length?upper:best.value,nodes}:null}
function nodeAllocation(cfg,rs,r){let ns=Array(r.length).fill(0),left=wasteRate(cfg)/12;for(let i=0;i<r.length;i++)if(rs[i].node&&rs[i].id==='mid'){ns[i]=Math.min(left,r[i]/.2);left-=ns[i]}for(let i=0;i<r.length;i++)if(rs[i].node&&left>0){ns[i]=Math.min(left,r[i]/.2);left-=ns[i]}return ns}
function evaluate(cfg,rs,r){const ns=nodeAllocation(cfg,rs,r),raw=[0,0,0,0],groups={},count={};let gas=0,rev=0,bottles=0;rs.forEach((p,i)=>{for(let j=0;j<4;j++)raw[j]+=p.raw[j]*r[i];raw[3]-=9.6*ns[i];gas+=p.reaction*r[i];rev+=p.price*p.out*r[i];if(p.bottle)bottles+=p.out*r[i];if(p.up)groups['up'+p.up]=(groups['up'+p.up]||0)+(p.bottle?4:2)*r[i];if(p.end)groups[p.end]=(groups[p.end]||0)+p.endCap*r[i];if(p.furnace)groups.furnace=(groups.furnace||0)+r[i];if(p.environment)groups[p.environment]=(groups[p.environment]||0)+r[i]/p.occupancyCapacity;if(p.customActivation)groups[p.customActivation.key]=(groups[p.customActivation.key]||0)+r[i]});for(const[k,v]of Object.entries(groups)){count[k]=(k.startsWith('up')||k.startsWith('dragon'))?2*Math.ceil(v/2-1e-7):Math.ceil(v-1e-7);const meta=rs.find(p=>p.customActivation?.key===k)?.customActivation;if(meta){if(meta.resource===4)gas+=meta.cost*count[k];else raw[meta.resource]+=meta.cost*count[k]}else if(k==='upL')raw[3]+=6*count[k];else if(k==='furnace')raw[3]+=30*count[k];else if(k.startsWith('env'))raw[3]+=cfg.acidCost*count[k];else gas+=6*count[k]}const deficit=Math.max(0,gas-cfg.gas);let B=0,nc=0,extra=0;let found=deficit<1e-7;if(!found)for(let n=1;n<=Math.ceil(cfg.solid/6)+1;n++){let need=cfg.conversion==='S'?deficit+6*n:deficit;for(let k=0;k<=n;k++)for(const t of T){let v=30*k+t;if(v>30*n+1e-7||Math.ceil((v-1e-7)/30)!==n||v<need-1e-7)continue;let e=v+(cfg.conversion==='L'?6*n:0);if(!found||e<extra){B=v;nc=n;extra=e;found=true}}if(found&&30*n>extra+30)break}raw[3]+=extra;const caps=[cfg.ore+2*cfg.powder/60,cfg.blue+cfg.blueTransport/60,cfg.copper,cfg.solid];let feasible=found&&raw.every((v,i)=>v<=caps[i]+1e-6)&&['mid','low'].every(id=>rs.reduce((s,p,i)=>s+(p.id===id?p.out*r[i]:0),0)>=powerFor(cfg,id)-1e-7);return{r,ns,raw,count,gas,B,nc,rev:rev-powerCost(cfg),bottles,feasible,externalGas:Math.min(cfg.gas,Math.max(0,gas-(cfg.conversion==='S'?B-6*nc:B)))}}
function rates(cfg,rs,i,max){let p=rs[i],a=new Set([0]);let coefficients=(p.id==='mid'?[p.raw[1],p.raw[3]]:p.raw).filter(v=>v>0).concat(p.reaction>0?[p.reaction]:[]);for(let k=0;k<=Math.ceil(max*Math.max(...coefficients,30)/30);k++)for(const t of T){let s=30*k+t;for(const c of coefficients){let v=s/c;if(v<=max+1e-7)a.add(+v.toFixed(9))}if(p.node){let q=(s+.8*wasteRate(cfg))/p.raw[3];if(q<=max+1e-7&&q>=wasteRate(cfg)/60)a.add(+q.toFixed(9))}}return [...a].sort((a,b)=>a-b)}
function engineer(m,s){const cfg=m.cfg,rs=m.recipes;const lists=rs.map((p,i)=>rates(cfg,rs,i,Math.max(2,s.x[i]*1.6+1)));let initial=s.x.slice(0,m.n).map((v,i)=>lists[i].filter(x=>x<=v+1e-7).pop()||0);initial=initial.map((v,i)=>Math.max(v,lists[i].find(x=>rs[i].out*x>=powerFor(cfg,rs[i].id)-1e-7)??v));let init=evaluate(cfg,rs,initial),beam=[init],best=null;const visited=new Set;function score(v){if(m.goal===1)return v.rev;const shortage=Math.max(0,cfg.threshold/60-v.rev);return shortage>1e-7?-1e5-shortage*100+v.bottles:v.bottles*1e6-(v.rev-cfg.threshold/60)}let start=Date.now();for(let iter=0;iter<32&&Date.now()-start<10000;iter++){let next=[];for(const v of beam){if(v.feasible&&(m.goal===1||v.rev>=cfg.threshold/60-1e-7)&&(!best||score(v)>score(best)))best=v;for(let i=0;i<m.n;i++){let idx=lists[i].findIndex(x=>Math.abs(x-v.r[i])<1e-7);for(let d of [-1,1,2,3]){let j=idx+d;if(j<0||j>=lists[i].length)continue;let r=v.r.slice();r[i]=lists[i][j];let key=r.join(',');if(visited.has(key))continue;visited.add(key);let x=evaluate(cfg,rs,r);if(x.feasible)next.push(x)}}}next.sort((a,b)=>score(b)-score(a));beam=next.slice(0,20);if(!beam.length)break}return best}
function solvePlan(cfg,goal,seed=null){let routes=goal===1?[null]:['bottleA','bottleS'].concat(cfg.liquid?['bottleL']:[]),best=null;for(const route of routes){let m=build(cfg,goal,route);let s=m.ints.length?mip(m,2500,seedSolution(m,seed)):lp(m.A,m.b,m.obj);if(!s)continue;if(cfg.mode==='engineering'){const e=engineer(m,s);if(!e)continue;let candidate={...e,customEquipment:Object.fromEntries(m.recipes.filter(p=>p.customActivation).map(p=>[p.customActivation.key,p.customActivation])),recipes:m.recipes,mode:cfg.mode,upper:s.upper??s.value,certificate:'有限取料候选搜索；收益/瓶产量上界来自连续普通料＋整数激活机台模型',exact:false};if(!best||(goal===1?candidate.rev>best.rev: candidate.bottles>best.bottles+1e-7||Math.abs(candidate.bottles-best.bottles)<1e-7&&candidate.rev<best.rev))best=candidate;continue}
 const objectiveUpper=s.upper??s.value;
 if(goal===2){let P=s.x.reduce((v,x,i)=>v+(m.recipes[i]?.bottle?m.recipes[i].out*x:0),0);const a=m.obj.map(v=>-v);let minModel={...m,A:m.A.concat([a]),b:m.b.concat([-P+1e-6]),obj:m.costs.map(v=>-v)};let t=minModel.ints.length?mip(minModel,1000,s):lp(minModel.A,minModel.b,minModel.obj);if(t)s=t}
 let r=s.x.slice(0,m.n),e;if(cfg.mode==='integer'){e=evaluate(cfg,m.recipes,r);let actual=30*s.x[m.conv];e.raw[3]+=actual-e.B;e.B=actual;e.nc=s.x[m.convN];e.externalGas=Math.max(0,e.gas-(cfg.conversion==='S'?actual-6*e.nc:actual));}else{let raw=m.resource.map(row=>row.reduce((v,x,i)=>v+x*s.x[i],0));let rev=m.costs.reduce((v,x,i)=>v+x*s.x[i],0)-powerCost(cfg);let count=Object.fromEntries(Object.entries(m.equipment).map(([k,j])=>[k,s.x[j]]));let ns=r.map((v,i)=>{let j=m.vars.indexOf('node_'+m.recipes[i].id);return j<0?0:s.x[j]});e={r,raw:raw.slice(0,4),ns,count,rev,bottles:r.reduce((v,x,i)=>v+(m.recipes[i].bottle?m.recipes[i].out*x:0),0),B:30*s.x[m.conv],nc:m.convN<0?s.x[m.conv]:s.x[m.convN],gas:raw[4]+(cfg.conversion==='S'?24:30)*s.x[m.conv],netExternalGas:raw[4],gasSurplus:Math.max(0,-raw[4]),externalGas:Math.max(0,raw[4]),feasible:true}}
 let candidate={...e,customEquipment:Object.fromEntries(m.recipes.filter(p=>p.customActivation).map(p=>[p.customActivation.key,p.customActivation])),recipes:m.recipes,mode:cfg.mode,exact:!m.ints.length||s.exact,certificate:cfg.mode==='continuous'?(s.exact||!m.ints.length?'连续流量＋整数占用模型已完成搜索':'连续流量＋整数占用搜索达到时间限制，当前可行解'):s.exact?'整数模型已完成搜索':'整数搜索达到时间限制，当前可行解',upper:goal===1?objectiveUpper-powerCost(cfg):objectiveUpper};if(!best||(goal===1?candidate.rev>best.rev:candidate.bottles>best.bottles+1e-7||Math.abs(candidate.bottles-best.bottles)<1e-7&&candidate.rev<best.rev))best=candidate}return best}
function validate(cfg){for(const k of ['ore','blue','copper','solid','gas','powder','blueTransport','power','threshold','acidCost'])if(!Number.isFinite(cfg[k])||cfg[k]<0||cfg[k]>1e6)throw Error('资源与额度必须为0至1000000的有限数值');if(cfg.waste!==undefined&&(!Number.isFinite(cfg.waste)||cfg.waste<0))throw Error('废液速率必须为非负有限数值');if(cfg.lowPower!==undefined&&(!Number.isFinite(cfg.lowPower)||cfg.lowPower<0||cfg.lowPower>1e6))throw Error('低电自用量必须为0至1000000');if(!cfg.free&&!cfg.products.length)throw Error('至少选择一种商品');}
function calculate(cfg){validate(cfg);if(cfg.unifiedFree)return{free:solveUnified(cfg)};if(cfg.free)return{free:solveFree(cfg)};if(cfg.calcGoal===1)return{first:solvePlan(cfg,1)};if(cfg.calcGoal===2)return{second:solveExpectation(cfg)};const first=solvePlan(cfg,1);return{first,second:cfg.expectTargets?solveExpectation(cfg):solvePlan(cfg,2,first)}}
if(typeof module!=='undefined')module.exports={lp,PRODUCTS,build,solvePlan,calculate,evaluate,solveFree,splitTheory,solveExpectation,compileExpectProducts,solveFreeExtended,solveUnified,solveUnifiedPhase};
function planFromVector(m,s){const r=s.x.slice(0,m.n),raw=m.resource.map(a=>a.reduce((v,x,i)=>v+x*s.x[i],0));const count=Object.fromEntries(Object.entries(m.equipment).map(([k,j])=>[k,s.x[j]]));const ns=r.map((v,i)=>{const j=m.vars.indexOf('node_'+m.recipes[i].id);return j<0?0:s.x[j]});const B=30*s.x[m.conv],nc=m.convN<0?s.x[m.conv]:s.x[m.convN];return{r,ns,raw:raw.slice(0,4),count,B,nc,netExternalGas:raw[4],gasSurplus:Math.max(0,-raw[4]),externalGas:Math.max(0,raw[4]),gas:raw[4]+(m.cfg.conversion==='S'?(m.convN<0?24* s.x[m.conv]:B-6*nc):B),rev:m.costs.reduce((v,x,i)=>v+x*s.x[i],0)-powerCost(m.cfg),bottles:r.reduce((v,x,i)=>v+(m.recipes[i].bottle?m.recipes[i].out*x:0),0),recipes:m.recipes,mode:m.cfg.mode,feasible:true,exact:s.exact??true,upper:s.upper??s.value,certificate:s.exact===false?'搜索到当前可行方案，尚未证明最大值':'模型搜索完成'}}
function freeResourceRows(c,p){const caps=[c.ore+2*c.powder/60,c.blue+c.blueTransport/60,c.copper,c.solid,c.gas],usage=[...p.raw,p.externalGas];return caps.map((cap,i)=>({name:['原矿等价量','蓝铁等价量','赤铜','息壤','天然息壤气'][i],capacity:cap,producedSurplus:Math.max(0,-usage[i]),used:Math.max(0,Math.abs(usage[i])<1e-7?0:usage[i]),remaining:Math.abs(cap-Math.max(0,usage[i]))<1e-7?0:cap-Math.max(0,usage[i]),shortage:Math.max(0,usage[i]-cap)}))}
function solveFree(cfg){if(cfg.freeOtherTargets?.length)return solveFreeExtended(cfg);
 const ts=cfg.freeTargets;if(!Array.isArray(ts)||!ts.length)throw Error('请填写自由产率');if(ts.filter(t=>t.maximize).length>1)throw Error('一次只能最大化一种产物');for(const t of ts){if(!Number.isFinite(t.qty)||t.qty<0||t.qty>10000)throw Error('产率必须为0至10000的有限数值');if(t.qty>0||t.maximize||powerFor(cfg,t.name==='中电'?'mid':t.name==='低电'?'low':'')>0){if(!PRODUCTS.some(p=>p.name===t.name&&(t.route==='auto'||p.id===t.route)&&(!p.id.endsWith('L')||cfg.liquid)&&(!p.activity||cfg.activity)))throw Error(t.name+'的工艺被当前预设禁止')}}
 const max=ts.find(t=>t.maximize),b=ts.find(t=>t.name==='赫铜瓶');const br=b&&(b.qty>0||b.maximize)?(b.route==='auto'?['bottleA','bottleS',...(cfg.liquid?['bottleL']:[])]:[b.route]):[null];let best=null,diagnostic=null,allProven=true,globalUpper=-Infinity;
 for(const route of br){const c={...cfg,freeBottleRoute:route},m=build(c,3,route);let s=m.ints.length?mip(m,5000):lp(m.A,m.b,m.obj);if(s){let bound=s.upper??s.value;globalUpper=Math.max(globalUpper,bound);allProven&&=s.exact!==false;const locked=m.obj.map(v=>-v);const min={...m,A:m.A.concat(max?[locked]:[]),b:m.b.concat(max?[-s.value+1e-7]:[]),obj:m.vars.map((_,i)=>-m.resource.slice(0,4).reduce((v,a,j)=>v+a[i]/[30,30,30,30,120][j],0))};const t=min.ints.length?mip(min,2000,s):lp(min.A,min.b,min.obj);if(t)s=t;const p=planFromVector(m,s);p.upper=bound;p.maxRate=max?p.recipes.reduce((v,r,i)=>v+(r.name===max.name?r.out*p.r[i]:0),0):null;p.exact=allProven&&s.exact!==false;if(!best||p.maxRate>best.maxRate+1e-6||Math.abs((p.maxRate||0)-(best.maxRate||0))<1e-6&&p.raw[3]<best.raw[3])best=p;continue;}
 if(lp(m.A,m.b,m.obj))allProven=false;
 // A separate minimax shortage model keeps the requested rates and exposes bottlenecks.
 const d=build({...c,mode:cfg.mode==='integer'?'engineering':cfg.mode},3,route),old=d.vars.length;for(let i=0;i<5;i++){d.vars.push('shortage_'+i);for(const a of d.A)a.push(0);for(const a of d.resource)if(!d.A.includes(a))a.push(0);d.costs.push(0)}d.vars.push('largest_relative_shortage');for(const a of d.A)a.push(0);for(const a of d.resource)if(!d.A.includes(a))a.push(0);d.costs.push(0);const z=old+5;
 d.obj=Array(d.vars.length).fill(0);d.obj[z]=-1;for(let i=0;i<5;i++){const ri=d.A.indexOf(d.resource[i]);d.A[ri][old+i]=-1;const a=Array(d.vars.length).fill(0);a[old+i]=1;a[z]=-Math.max(1,d.caps[i]);d.A.push(a);d.b.push(0)}
 // Maximize checkbox means a lower bound here, not an extra optimization demand.
 const q=d.ints.length?mip(d,5000):lp(d.A,d.b,d.obj);if(q){const p=planFromVector(d,q);p.externalGas+=q.x[old+4];for(let i=0;i<4;i++)p.raw[i]+=q.x[old+i];p.resourceRows=freeResourceRows(c,p);p.maxRate=max?ts.find(t=>t.name===max.name).qty:null;p.feasible=false;p.diagnosticExact=q.exact!==false;if(!diagnostic||q.value>diagnostic.score)diagnostic={...p,score:q.value};}
 }
 if(best){best.exact=best.exact&&allProven;best.upper=globalUpper;best.resourceRows=freeResourceRows(cfg,best);best.feasible=true;best.maxName=max?.name;best.certificate=best.exact?'自由约束模型搜索完成': '当前可行解；达到搜索限制，最大值尚未证明';return best}
 if(diagnostic){const integerMismatch=cfg.mode==='integer'&&ts.some(t=>!t.maximize&&Math.max(t.qty,powerFor(cfg,t.name==='中电'?'mid':t.name==='低电'?'low':''))>0&&PRODUCTS.filter(p=>p.name===t.name&&(t.route==='auto'||t.route===p.id)).every(p=>Math.abs(Math.max(t.qty,powerFor(cfg,p.id))/p.out-Math.round(Math.max(t.qty,powerFor(cfg,p.id))/p.out))>1e-7));diagnostic.reason=integerMismatch?'整数模式要求满速线数为整数；输入产率与此要求不符。':diagnostic.resourceRows.some(r=>r.shortage>1e-6)?'指定产率超出资源容量，以下为最小化最大相对缺口后的一种诊断配方组合。': '搜索未找到满足当前模式的方案；不能据此判定数学上无解。';diagnostic.status=integerMismatch||diagnostic.resourceRows.some(r=>r.shortage>1e-6)&&diagnostic.diagnosticExact?'不可实现':'尚未找到可行方案';return diagnostic}
 return{feasible:false,status:'尚未找到可行方案',reason:'检查工艺、供电与产率约束；未获得可用于列出资源缺口的配方组合。',resourceRows:[]};
}
function splitTheory(value,pipe=false){const capacity=pipe?120:30,Q=capacity/2;const whole=Math.floor((value+1e-8)/Q),tail=Math.max(0,value-whole*Q);if(tail<1e-7)return{whole,Q,tail:0,capacity};const scaled=Math.round(tail*1e6),base=Q*1e6;function gcd(a,b){while(b){[a,b]=[b,a%b]}return a}const g=gcd(scaled,base),a=scaled/g,b=base/g,k=Math.ceil(Math.log2(b)),N=2**k,T=N*Q/b;
 const chunks=[];function walk(start,size,depth,path){const end=start+size;let category=end<=a?'取用':start>=a&&end<=b?'余料回存':start>=b?'回流':'分流';if(category!=='分流'){chunks.push({category,depth,path:path||'主干',flow:T*size/N});return}walk(start,size/2,depth+1,path+'左');walk(start+size/2,size/2,depth+1,path+'右')}walk(0,N,0,'');return{whole,Q,tail,capacity,a,b,k,N,T,feedback:N-b,chunks,rounding:Math.abs(a*Q/b-tail)}}

const EXPECT_ALIASES={'低容武陵电池':'低电','中容武陵电池':'中电','芽针针剂':'蓝药','优质芽针针剂':'紫药','赫铜零件':'赫铜','重息壤':'重息壤','灼铜零件':'灼铜','赫铜瓶':'赫铜瓶'};
function compileExpectProducts(c){const rs=c.expectCatalog||[],targets=c.expectTargets.filter(t=>t.name),extras=[],needed=new Set,visiting=new Set;const base={'源矿':0,'原矿':0,'蓝铁矿':1,'赤铜矿':2,'息壤':3,'液化息壤':3,'息壤气':4},unlimited=new Set(['砂叶','清水','污水','惰气','沉积酸']);const boundary=new Set(Object.keys(base));
function visit(item){if(boundary.has(item)||unlimited.has(item)||visiting.has(item))return;visiting.add(item);for(const r of rs){if(!r.inputs.length||!r.outputs.some(o=>o.item===item&&o.amount>0)||!r.seconds)continue;if(r.catalyst==='液化息壤'&&!c.liquid)continue;if(!c.activity&&r.outputs.some(o=>o.item.includes('龙泡泡')))continue;needed.add(r.id);for(const x of r.inputs)visit(x.item);if(r.catalyst&&!boundary.has(r.catalyst)&&!unlimited.has(r.catalyst))visit(r.catalyst)}visiting.delete(item)}
for(const [i,t] of targets.entries()){const alias=EXPECT_ALIASES[t.name]|| (PRODUCTS.some(p=>p.name===t.name)?t.name:null);if(alias){for(const p of PRODUCTS.filter(p=>p.name===alias&&(!p.id.endsWith('L')||c.liquid)&&(!p.activity||c.activity)))extras.push({...p,raw:p.raw.slice(),id:'keep_'+i+'_'+p.id,sourceId:p.id,name:t.name,price:0,expect:true,target:i,node:p.node});}else{visit(t.name);const raw=[0,0,0,0],reaction=base[t.name]===4?1:0;if(base[t.name]!==undefined&&base[t.name]<4)raw[base[t.name]]=1;extras.push({id:'withdraw_'+i,name:t.name,route:'自用留存',out:1,raw,reaction,price:0,expect:true,target:i,withdraw:true,flowInputs:boundary.has(t.name)?{}:{[t.name]:1},flowOutputs:{}})}}
for(const r of rs.filter(r=>needed.has(r.id))){const raw=[0,0,0,0],fi={},fo={};let gas=0;for(const [list,sign,flow] of [[r.inputs,1,fi],[r.outputs,-1,fo]])for(const x of list){if(!(x.amount>0))continue;const rate=x.amount*60/r.seconds;if(base[x.item]!==undefined){if(base[x.item]===4)gas+=sign*rate;else raw[base[x.item]]+=sign*rate;}else if(!unlimited.has(x.item))flow[x.item]=(flow[x.item]||0)+rate}
let activation=null;if(r.catalyst&&r.catalystPerMinute>0){const idx=base[r.catalyst];if(idx!==undefined)activation={key:'custom_'+r.id,resource:idx,cost:r.catalystPerMinute,name:r.machine+' · '+r.catalyst+'激活'};else if(!unlimited.has(r.catalyst))throw Error(r.catalyst+'激活尚无基础资源口径，无法计算该目标')}
extras.push({id:'network_'+r.id,name:'加工 · '+r.outputs.map(x=>x.item).join('／'),route:r.machine,out:r.outputs[0].amount*60/r.seconds,raw,reaction:gas,price:0,expect:true,network:true,flowInputs:fi,flowOutputs:fo,customActivation:activation,...(r.environment==='酸性环境'?{environment:'envScorch',occupancyCapacity:4,occupancy:c.acidCost}:{}),sourceRecipe:r});}
return extras}
function expectAddVariable(m,name,integer=false){const j=m.vars.length;m.vars.push(name);m.obj.push(0);m.costs.push(0);for(const a of m.A)a.push(0);for(const a of m.resource)if(!m.A.includes(a))a.push(0);if(integer)m.ints.push(j);return j}
function expectRow(m,entries,b){const a=Array(m.vars.length).fill(0);for(const [i,v] of entries)a[i]=v;m.A.push(a);m.b.push(b)}
function expectGrid(m,i,coef,offsets=[]){if(coef<=0)return;const k=expectAddVariable(m,'gridWhole_'+i,true),tails=T.filter(x=>x<30).map((v,j)=>[expectAddVariable(m,'gridTail_'+i+'_'+j,true),v]);for(const [j] of tails)expectRow(m,[[j,1]],1);expectRow(m,tails.map(([j])=>[j,1]),1);expectRow(m,tails.map(([j])=>[j,-1]),-1);const entries=[[i,coef],...offsets,[k,-30],...tails.map(([j,v])=>[j,-v])];expectRow(m,entries,0);expectRow(m,entries.map(([j,v])=>[j,-v]),0);(m.grids??=[]).push({i,coef,k,tails,offsets})}
function solveExpectation(cfg){const targets=cfg.expectTargets.filter(t=>t.name);if(!targets.length){const p=solvePlan(cfg,1);if(!p||p.rev<cfg.threshold/60-1e-6)return null;return{...p,priority:[],certificate:p.certificate+'；自用目标为空，仅校验售卖价值是否达到期望额度。'}}if(targets.length>5||new Set(targets.map(t=>t.name)).size!==targets.length)throw Error('期望兑换最多5个不同产物');for(const t of targets)if(!Number.isFinite(t.min)||t.min<0||t.min>10000)throw Error('调整产率必须为0至10000');const extras=compileExpectProducts(cfg),routes=extras.some(p=>p.bottle)?['bottleA','bottleS',...(cfg.liquid?['bottleL']:[])]:[null];let best=null;
let allProven=true;const legacy=cfg.mode==='engineering'&&targets.some(t=>t.name==='赫铜瓶')?solvePlan({...cfg,expectTargets:undefined,expectExtras:undefined},2):null;if(legacy){const preferred=legacy.recipes.find((p,i)=>p.bottle&&legacy.r[i]>1e-6)?.id;routes.sort((a,b)=>(b===preferred?1:0)-(a===preferred?1:0));}for(const route of routes){const c={...cfg,expectExtras:extras},m=build(c,2,route),items=new Set;m.recipes.forEach(p=>{Object.keys(p.flowInputs||{}).forEach(x=>items.add(x));Object.keys(p.flowOutputs||{}).forEach(x=>items.add(x))});for(const item of items){const a=m.recipes.map((p,i)=>[i,(p.flowInputs?.[item]||0)-(p.flowOutputs?.[item]||0)]);expectRow(m,a,0);if(entries.some(t=>t.name===item))expectRow(m,a.map(([i,v])=>[i,-v]),0);}
const vectors=targets.map((t,j)=>m.vars.map((_,i)=>m.recipes[i]?.target===j?m.recipes[i].out:0));for(let j=0;j<targets.length;j++)expectRow(m,vectors[j].map((v,i)=>[i,-v]),-targets[j].min);
m.obj=m.vars.map((_,i)=>vectors[0]?.[i]||0);const routeBound=lp(m.A,m.b,m.obj);if(!routeBound)continue;if(best&&routeBound.value<best.priority[0].rate-1e-6)continue;let structural=null,seed=null;if(cfg.mode==='engineering'){if(legacy){const sm={...m,A:m.A.map(a=>a.slice()),b:m.b.slice(),vars:m.vars.slice(),obj:m.obj.slice()};const vector=expectVector(sm,legacy);for(let i=0;i<sm.n;i++)if(!sm.recipes[i].expect){expectRow(sm,[[i,1]],vector.x[i]);expectRow(sm,[[i,-1]],-vector.x[i]);}for(const [name,j] of Object.entries(sm.equipment))if(!name.startsWith('custom_')){expectRow(sm,[[j,1]],vector.x[j]);expectRow(sm,[[j,-1]],-vector.x[j]);}for(let i=sm.n;i<sm.vars.length;i++)if(sm.vars[i].startsWith('node_')||i===sm.conv||i===sm.convN){expectRow(sm,[[i,1]],vector.x[i]);expectRow(sm,[[i,-1]],-vector.x[i]);}for(let i=0;i<sm.n;i++)if(sm.recipes[i].network&&sm.recipes[i].customActivation)expectRow(sm,[[i,1]],0);structural=lp(sm.A,sm.b,sm.obj);if(structural){for(let i=0;i<sm.n;i++)if(sm.recipes[i].expect&&sm.recipes[i].bottle){const coef=Math.max(...sm.recipes[i].raw),v=coef*structural.x[i],whole=Math.floor((v+1e-7)/30),tail=v-30*whole,rest=T.filter(t=>t<=tail+1e-7).pop()||0;const r=(whole*30+rest)/coef;expectRow(sm,[[i,1]],r);expectRow(sm,[[i,-1]],-r);}sm.obj=sm.vars.map((_,i)=>sm.recipes[i]?.expect&&!sm.recipes[i]?.bottle?-Math.max(1,sm.recipes[i].out):0);structural=lp(sm.A,sm.b,sm.obj);}}const seedModel={...m,A:m.A.map(a=>a.slice()),b:m.b.slice(),ints:[...new Set(m.ints.concat(m.recipes.map((p,i)=>p.withdraw?-1:i).filter(i=>i>=0),[m.conv]))],obj:m.vars.map((_,i)=>targets.length?(vectors[0][i]||0):m.costs[i])};const saleSeed=solvePlan({...cfg,mode:'integer',expectTargets:undefined,expectExtras:undefined},1);seed=mip(seedModel,1500,expectVector(seedModel,saleSeed));for(let i=0;i<m.n;i++){const p=m.recipes[i];if(p.withdraw)continue;let coef=Math.max(...p.raw,Math.max(0,p.reaction)),offsets=[];if(p.node){coef=p.raw[3];const j=m.vars.indexOf('node_'+p.id);if(j>=0)offsets.push([j,-9.6]);}if(!coef)coef=Object.values(p.flowInputs||{}).find(v=>v>0)||Math.max(0,p.reaction);if(p.network){const input=p.sourceRecipe.inputs.find(x=>x.amount>0);if(input)coef=input.amount*60/p.sourceRecipe.seconds;}if(coef)expectGrid(m,i,coef,offsets)}expectGrid(m,m.conv,30)}
if(seed){seed={...seed,x:seed.x.concat(Array(m.vars.length-seed.x.length).fill(0))};for(const g of m.grids||[]){const v=g.coef*seed.x[g.i]+g.offsets.reduce((n,[j,v])=>n+v*seed.x[j],0),whole=Math.floor((v+1e-7)/30),tail=v-30*whole,match=g.tails.find(([,t])=>Math.abs(t-tail)<1e-5);if(!match){seed=null;break}seed.x[g.k]=whole;seed.x[match[0]]=1;}}if(structural){const candidate={x:structural.x.concat(Array(m.vars.length-structural.x.length).fill(0))};for(const g of m.grids||[]){const v=g.coef*candidate.x[g.i]+g.offsets.reduce((n,[j,v])=>n+v*candidate.x[j],0),whole=Math.floor((v+1e-7)/30),tail=v-30*whole,match=g.tails.find(([,t])=>Math.abs(t-tail)<1e-5);if(match){candidate.x[g.k]=whole;candidate.x[match[0]]=1}}const valid=validSolution(m,candidate);if(valid)seed=valid;}if(legacy){const values={conversion:legacy.B/30,converter:legacy.nc};legacy.recipes.forEach((p,i)=>{values[p.id]=legacy.r[i];values['node_'+p.id]=legacy.ns?.[i]||0});for(const [k,v] of Object.entries(legacy.count)){values[k]=v;values['chains_'+k]=v/2}for(const p of m.recipes.filter(p=>p.expect&&p.bottle))values[p.id]=values[p.sourceId]||0;const candidate=expectVector(m,legacy)||{x:Array(m.vars.length).fill(0)};for(const g of m.grids||[]){const v=g.coef*candidate.x[g.i]+g.offsets.reduce((n,[j,v])=>n+v*candidate.x[j],0),whole=Math.floor((v+1e-7)/30),tail=v-30*whole,match=g.tails.find(([,t])=>Math.abs(t-tail)<1e-5);if(match){candidate.x[g.k]=whole;candidate.x[match[0]]=1}}const valid=validSolution(m,candidate);if(valid&&(!seed||targets.reduce((n,t,j)=>n+(vectors[j].reduce((a,v,i)=>a+v*valid.x[i],0)-vectors[j].reduce((a,v,i)=>a+v*seed.x[i],0))*Math.pow(1e3,targets.length-j),0)>0))seed=valid;}let exact=true,s=seed,locks=[],values=[];for(let j=0;j<Math.max(1,targets.length);j++){m.obj=Array(m.vars.length).fill(0);if(targets.length)vectors[j].forEach((v,i)=>m.obj[i]=v);else m.costs.forEach((v,i)=>m.obj[i]=-v);s=m.ints.length?mip(m,cfg.mode==='engineering'?200:4000,s):lp(m.A,m.b,m.obj);if(!s)break;exact&&=s.exact!==false;const value=targets.length?m.obj.reduce((n,v,i)=>n+v*s.x[i],0):0;values.push(value);if(targets.length){const a=m.obj.map(v=>-v);m.A.push(a);m.b.push(-value+1e-7);locks.push(value)}}if(!s){allProven=false;continue;}allProven&&=exact;
// Minimize normalized ordinary resource consumption without changing priority optima.
m.obj=m.vars.map((_,i)=>-m.resource.slice(0,4).reduce((v,a,j)=>v+a[i]/[30,30,30,30,120][j],0));const min=m.ints.length?mip(m,cfg.mode==='engineering'?200:4000,s):lp(m.A,m.b,m.obj);if(min)s=min;const p=planFromVector(m,s);p.exact=exact;p.priority=targets.map((t,j)=>({...t,rate:m.recipes.reduce((n,r,i)=>n+(r.target===j?r.out*p.r[i]:0),0)}));p.customEquipment=Object.fromEntries(m.recipes.filter(p=>p.customActivation).map(p=>[p.customActivation.key,p.customActivation]));p.upper=values[0]||0;p.certificate=(exact?'按优先级依次完成模型搜索':'按优先级返回当前可行候选，搜索达到限制，尚未证明全局最优')+'；自用目标不计售卖价值。';if(cfg.mode==='engineering')p.certificate+='工程取货采用整口＋允许尾量约束，激活机台取整数。';const compare=(a,b)=>{for(let j=0;j<targets.length;j++){const d=a.priority[j].rate-b.priority[j].rate;if(Math.abs(d)>1e-6)return d}return b.rev-a.rev};if(!best||compare(p,best)>0)best=p;
}if(best&&!allProven){best.exact=false;best.certificate='按优先级返回当前可行候选，部分工艺搜索未完成，尚未证明全局最优；自用目标不计售卖价值。';}return best}

function expectVector(m,p){if(!p)return null;const x=Array(m.vars.length).fill(0);m.recipes.forEach((r,i)=>{if(r.expect&&!r.bottle)return;const k=p.recipes.findIndex(t=>t.id===(r.sourceId||r.id));if(k>=0)x[i]=p.r[k]});for(const [name,j] of Object.entries(m.equipment))x[j]=p.count[name]||0;x[m.conv]=p.B/30;if(m.convN>=0)x[m.convN]=p.nc;for(let i=m.n;i<m.vars.length;i++){const name=m.vars[i];if(name.startsWith('node_')){const k=p.recipes.findIndex(t=>'node_'+t.id===name);if(k>=0)x[i]=p.ns?.[k]||0}if(name.startsWith('chains_'))x[i]=(p.count[name.slice(7)]||0)/2;}return{x};}

function solveFreeExtended(cfg){const others=cfg.freeOtherTargets,regular=cfg.freeTargets.filter(t=>!t.other),max=cfg.freeTargets.find(t=>t.maximize);if(cfg.freeTargets.filter(t=>t.maximize).length>1)throw Error('自由模式一次只能最大化一种产物');for(const t of cfg.freeTargets)if(!Number.isFinite(t.qty)||t.qty<0||t.qty>10000)throw Error('自由产率应为0至10000');if(new Set(cfg.freeTargets.map(t=>t.name)).size!==cfg.freeTargets.length)throw Error('自由产物不能重复选择');const c={...cfg,free:false,threshold:0,expectTargets:others.map(t=>({name:t.name,min:t.qty})),products:regular.map(t=>t.name)};const extras=compileExpectProducts(c),routes=extras.some(p=>p.bottle)?['bottleA','bottleS',...(cfg.liquid?['bottleL']:[])]:[null];let best=null,diagnostic=null,allProven=true;
for(const route of routes){const m=build({...c,expectExtras:extras},2,route);const items=new Set;m.recipes.forEach(p=>{Object.keys(p.flowInputs||{}).forEach(x=>items.add(x));Object.keys(p.flowOutputs||{}).forEach(x=>items.add(x))});for(const item of items){const entries=m.recipes.map((p,i)=>[i,(p.flowInputs?.[item]||0)-(p.flowOutputs?.[item]||0)]);expectRow(m,entries,0);if(others.some(t=>t.name===item))expectRow(m,entries.map(([i,v])=>[i,-v]),0);}
m.obj=Array(m.vars.length).fill(0);for(const t of regular){const entries=m.recipes.map((p,i)=>[i,!p.expect&&p.name===t.name?p.out:0]);const q=Math.max(t.qty,powerFor(cfg,t.name==='中电'?'mid':t.name==='低电'?'low':''));expectRow(m,entries.map(([i,v])=>[i,-v]),-q);if(!t.maximize)expectRow(m,entries,q);else entries.forEach(([i,v])=>m.obj[i]=v);if(t.route!=='auto')m.recipes.forEach((p,i)=>{if(!p.expect&&p.name===t.name&&p.id!==t.route)expectRow(m,[[i,1]],0)});}
others.forEach((t,j)=>{const entries=m.recipes.map((p,i)=>[i,p.target===j?p.out:0]);expectRow(m,entries.map(([i,v])=>[i,-v]),-t.qty);if(!t.maximize)expectRow(m,entries,t.qty);else entries.forEach(([i,v])=>m.obj[i]=v)});
let s=m.ints.length?mip(m,3000):lp(m.A,m.b,m.obj);if(s){const bound=s.upper??s.value;allProven&&=s.exact!==false;const lock=m.obj.map(v=>-v);const min={...m,A:m.A.concat(max?[lock]:[]),b:m.b.concat(max?[-s.value+1e-7]:[]),obj:m.vars.map((_,i)=>-m.resource.slice(0,4).reduce((v,a,j)=>v+a[i]/[30,30,30,30,120][j],0))};const t=min.ints.length?mip(min,1500,s):lp(min.A,min.b,min.obj);if(t)s=t;const p=planFromVector(m,s);p.customEquipment=Object.fromEntries(m.recipes.filter(r=>r.customActivation).map(r=>[r.customActivation.key,r.customActivation]));p.maxName=max?.name;p.maxRate=max?m.recipes.reduce((n,r,i)=>n+(max.other?(r.target===others.findIndex(t=>t.name===max.name)?r.out*p.r[i]:0):!r.expect&&r.name===max.name?r.out*p.r[i]:0),0):null;
if(max?.other)p.maxRate=m.recipes.reduce((n,r,i)=>n+(r.target===others.findIndex(t=>t.name===max.name)?r.out*p.r[i]:0),0);p.upper=bound;p.exact=allProven&&s.exact!==false;p.otherOutputs=others.map((t,j)=>({...t,rate:m.recipes.reduce((n,r,i)=>n+(r.target===j?r.out*p.r[i]:0),0)}));p.resourceRows=freeResourceRows(cfg,p);p.certificate=p.exact?'自由模式扩展配方模型搜索完成':'自由模式返回可行候选，尚未证明最大值';if(!best||(p.maxRate||0)>(best.maxRate||0)+1e-6||Math.abs((p.maxRate||0)-(best.maxRate||0))<1e-6&&p.raw[3]<best.raw[3])best=p;continue;}
if(lp(m.A,m.b,m.obj))allProven=false;
const d={...m,vars:m.vars.slice(),A:m.A.map(a=>a.slice()),b:m.b.slice(),obj:m.obj.slice(),costs:m.costs.slice(),resource:m.resource.map(a=>a.slice()),ints:m.ints.filter(i=>cfg.mode!=='integer'||i>=m.n)};const capsRows=m.resource.map(a=>m.A.indexOf(a));const old=d.vars.length;const shortages=[];for(let i=0;i<5;i++)shortages.push(expectAddVariable(d,'shortage_'+i));const z=expectAddVariable(d,'largest_shortage');d.obj=Array(d.vars.length).fill(0);d.obj[z]=-1;for(let i=0;i<5;i++){d.A[capsRows[i]][shortages[i]]=-1;expectRow(d,[[shortages[i],1],[z,-Math.max(1,d.caps[i])]],0)}const q=d.ints.length?mip(d,2000):lp(d.A,d.b,d.obj);if(q){const p=planFromVector(d,q);p.resourceRows=freeResourceRows(cfg,p);p.feasible=false;p.status=p.resourceRows.some(r=>r.shortage>1e-6)&&q.exact!==false?'不可实现':'尚未找到可行方案';p.reason=p.resourceRows.some(r=>r.shortage>1e-6)?'指定产率超出基础资源容量，缺口见下表。':cfg.mode==='integer'?'指定产率可能不符合满速整数台要求；可尝试工程解或连续解。':'搜索未找到可行方案，不能据此判定数学上无解。';p.score=q.value;if(!diagnostic||p.score>diagnostic.score)diagnostic=p;}}
if(best){best.exact&&=allProven;return best}return diagnostic||{feasible:false,status:'尚未找到可行方案',reason:'检查工艺权限、供电和指定产率；未得到可用于诊断的配方组合。',resourceRows:[]};}

// Two-stage free planning. Fixed outputs are protected; prospective outputs are
// optimized lexicographically in the same resource model so shared costs count once.
function unifiedAlias(name){return EXPECT_ALIASES[name]||(PRODUCTS.some(p=>p.name===name)?name:null);}
function unifiedPrice(name){const a=unifiedAlias(name);return PRODUCTS.find(p=>p.name===a&&!p.bottle)?.price??null;}
function unifiedEntries(cfg,phase){const first=(cfg.fixedTargets||[]).map(t=>({...t,stage:'fixed',type:'fixed',qty:t.qty||0,min:0})),next=phase===2?(cfg.nextTargets||[]).map(t=>({...t,stage:'next',qty:t.type==='fixed'?t.fixed:0,min:t.type==='min'?t.min:0})):[];const all=first.concat(next);for(const t of all){if(!t.name)throw Error('请选择生产物品');for(const v of [t.qty||0,t.min||0])if(!Number.isFinite(v)||v<0||v>10000)throw Error('产率必须为0至10000的有限数值');}const auto=[];for(const[name,amount]of [['中电',cfg.power||0],['低电',cfg.lowPower||0]]){const existing=first.reduce((n,t)=>n+(unifiedAlias(t.name)===name?t.qty:0),0);if(existing<amount-1e-7)auto.push({name,route:'auto',stage:'power',type:'fixed',qty:amount-existing,min:0});}return first.concat(auto,next);}
function unifiedModel(cfg,entries,route){const c={...cfg,free:false,power:0,lowPower:0,threshold:0,products:[],expectTargets:entries.map(t=>({name:t.name,min:t.min||0}))};let extras=compileExpectProducts(c);extras=extras.filter(p=>{if(p.target!==undefined){const wanted=entries[p.target].route;return !wanted||wanted==='auto'||p.sourceId===wanted||p.withdraw;}if(p.network){return entries.every(t=>!t.route||t.route==='auto'||unifiedAlias(t.name)||!p.sourceRecipe.outputs.some(o=>o.item===t.name)||p.sourceRecipe.id===t.route);}return true;});const m=build({...c,expectExtras:extras},2,route);const items=new Set;m.recipes.forEach(p=>{Object.keys(p.flowInputs||{}).forEach(x=>items.add(x));Object.keys(p.flowOutputs||{}).forEach(x=>items.add(x));});for(const item of items){const a=m.recipes.map((p,i)=>[i,(p.flowInputs?.[item]||0)-(p.flowOutputs?.[item]||0)]);expectRow(m,a,0);if(entries.some(t=>t.name===item))expectRow(m,a.map(([i,v])=>[i,-v]),0);}
 const vectors=entries.map((t,j)=>m.vars.map((_,i)=>m.recipes[i]?.target===j?m.recipes[i].out:0));entries.forEach((t,j)=>{const v=vectors[j];expectRow(m,v.map((n,i)=>[i,-n]),-(t.type==='fixed'?t.qty:t.min||0));if(t.type==='fixed')expectRow(m,v.map((n,i)=>[i,n]),t.qty);});return {m,vectors};}
function unifiedPlan(cfg,m,s,entries,exact){if(!validSolution(m,s))throw Error('求解结果未通过资源及约束复核，请调整输入后重试。');const p=planFromVector(m,s);p.customEquipment=Object.fromEntries(m.recipes.filter(r=>r.customActivation).map(r=>[r.customActivation.key,r.customActivation]));p.outputs=entries.map((t,j)=>({...t,price:unifiedPrice(t.name),rate:m.recipes.reduce((n,r,i)=>n+(r.target===j?r.out*p.r[i]:0),0)}));p.priority=p.outputs.filter(t=>t.stage==='next');p.rev=p.outputs.reduce((n,t)=>n+(t.price??0)*t.rate,0)-powerCost(cfg);p.valueRows=p.outputs.map(t=>({...t,value:(t.price??0)*t.rate}));p.resourceRows=freeResourceRows(cfg,p);p.exact=exact;p.certificate=exact?'已完成固定产率保护与逐项优先级模型搜索。':'返回满足当前约束的候选；搜索达到限制，尚未证明各优先级全局最优。';if(cfg.mode==='engineering')p.certificate+='工程选项保留整数激活；全部原料接法见报告，未满足简单取货的条目不视为落地完成。';return p;}
function unifiedDiagnostic(cfg,m,entries){const d={...m,vars:m.vars.slice(),A:m.A.map(a=>a.slice()),b:m.b.slice(),obj:m.obj.slice(),costs:m.costs.slice(),resource:m.resource.map(a=>a.slice()),ints:m.ints.filter(i=>cfg.mode!=='integer'||i>=m.n)},capRows=m.resource.map(a=>m.A.indexOf(a)),ss=[];for(let i=0;i<5;i++)ss.push(expectAddVariable(d,'shortage_'+i));const z=expectAddVariable(d,'largest_shortage');d.obj=Array(d.vars.length).fill(0);d.obj[z]=-1;for(let i=0;i<5;i++){d.A[capRows[i]][ss[i]]=-1;expectRow(d,[[ss[i],1],[z,-Math.max(1,d.caps[i])]],0);}const s=d.ints.length?mip(d,1200):lp(d.A,d.b,d.obj);if(!s)return null;const p=unifiedPlan(cfg,d,s,entries,false);p.feasible=false;p.reason=p.resourceRows.some(r=>r.shortage>1e-5)?'基础资源不足，缺口见资源表。':'指定工艺或产率可能不符合当前解模式；未找到可行候选。';return p;}
function solveUnifiedPhase(cfg,phase){const entries=unifiedEntries(cfg,phase);const routes=entries.some(t=>unifiedAlias(t.name)==='赫铜瓶'||t.name==='赫铜瓶')?['bottleA','bottleS',...(cfg.liquid?['bottleL']:[])]:[null];let best=null,diagnostic=null,proven=true;
 for(const route of routes){const {m,vectors}=unifiedModel(cfg,entries,route);m.obj=Array(m.vars.length).fill(0);let s=m.ints.length?mip(m,2000):lp(m.A,m.b,m.obj),exact=true;if(!s){const d=unifiedDiagnostic(cfg,m,entries);if(d&&(!diagnostic||d.resourceRows.reduce((n,r)=>n+r.shortage,0)<diagnostic.resourceRows.reduce((n,r)=>n+r.shortage,0)))diagnostic=d;continue;}exact&&=s.exact!==false;
 for(let j=0;j<entries.length;j++){if(entries[j].stage!=='next'||entries[j].type==='fixed')continue;m.obj=vectors[j].slice();s=m.ints.length?mip(m,2000,s):lp(m.A,m.b,m.obj);if(!s)break;exact&&=s.exact!==false;const v=m.obj.reduce((n,a,i)=>n+a*s.x[i],0);expectRow(m,m.obj.map((a,i)=>[i,-a]),-v+1e-7);}
 if(!s){proven=false;continue;}m.obj=m.vars.map((_,i)=>-m.resource.slice(0,4).reduce((n,a,j)=>n+a[i]/Math.max(1,m.caps[j]),0));const t=m.ints.length?mip(m,1000,s):lp(m.A,m.b,m.obj);if(t)s=t;const p=unifiedPlan(cfg,m,s,entries,exact);proven&&=exact;const compare=(a,b)=>{for(let i=0;i<a.priority.length;i++){if(a.priority[i].type==='fixed')continue;const diff=a.priority[i].rate-b.priority[i].rate;if(Math.abs(diff)>1e-5)return diff;}return b.raw.reduce((n,v)=>n+v,0)-a.raw.reduce((n,v)=>n+v,0);};if(!best||compare(p,best)>0)best=p;}
 if(best){best.exact&&=proven;return best;}return diagnostic||{feasible:false,reason:'未找到满足指定工艺、产率与资源约束的方案。',resourceRows:[],outputs:[],priority:[]};}
function solveUnified(cfg){const baseline=solveUnifiedPhase(cfg,1);if(cfg.unifiedPhase===1||!baseline.feasible)return {...baseline,baseline,phase:1};const final=solveUnifiedPhase(cfg,2);return {...final,baseline,phase:2};}
